### ISSUE TITLE
illegal instruction error

### ISSUE THREAD

**Issue by fg6** [isovic/racon#10]
Hi,
I am trying to run racon on some nanopore yeast data but it crashes with the error:
 14645 Illegal instruction     $raconhome/bin/racon /s288c_ontreads_pass_plus2r9.fq mappings.paf layout_miniasm.fasta consensus.fasta

I was able to run a previous version of racon on the same data and using graphmap (github commit 28980bec3e98189853ed919764d5a8a9e6291264), but if I try the newest version with minimap, as suggested in the README I get the above error. Minimap seems to work fine and the contigs from miniasm look reasonable, so I don't know what can be wrong, can you help me figure it out? Thank you in advance for any help!

I ran it in this way:

`# create contigs from minimap+miniasm:`
`minimap -Sw5 -L100 -m0 -t8  s288c_ontreads_pass_plus2r9.fq  s288c_ontreads_pass_plus2r9.fq  |  gzip -1 > reads.paf.gz`
`miniasm -f s288c_ontreads_pass_plus2r9.fq  reads.paf.gz > reads.gfa`
`awk '$1 ~/S/ {print ">"$2"\n"$3}' reads.gfa > layout_miniasm.fasta`
`# align raw reads to raw contigs:`
`minimap layout_miniasm.fasta $reads > mappings.paf`
`# run racon:`
`$raconhome/bin/racon  s288c_ontreads_pass_plus2r9.fq   mappings.paf  layout_miniasm.fasta consensus.fasta`

The output is in the attached file.
[output.txt](https://github.com/isovic/racon/files/597235/output.txt)

I downloaded and installed racon like this:
git clone https://github.com/isovic/racon.git  && cd racon && make modules && make tools && make -j

I also tried to run racon on  the same data using as template the script example2-paf-pipe-lambda.sh, this created a consensus file, but crashed with the same error:

`...`
`...`
`[12:21:48 ConsensusDirectFromOverlaps] 	[25] utg000026l 28 alignments, contig len: 12064`
`[12:21:48 ConsensusDirectFromOverlaps] 	[26] utg000027l 67 alignments, contig len: 35001`
` `
`[12:21:48 ConsensusDirectFromOverlaps] Started processing contig 1 / 27 (3.70%): utg000001l`
`[12:21:48 ConsensusDirectFromOverlaps] (thread_id = 0) Aligning overlaps for contig 1 / 27 (3.70%): utg000001l`
`[12:21:58 AlignOverlaps] Aligning overlap: 2547 / 2548 (100.00%), skipped 0 / 2548 (0.00%)`
`./example2-paf-pipe-lambda.sh: line 39: 37897 Done                    $raconhome/tools/minimap/minimap $contigs $reads`
`    37898 Illegal instruction     | $raconhome/bin/racon -M 5 -X -4 -G -8 -E -6 --bq 10 -t ${threads} ${reads} - ${contigs} ${consensus}`
`Racon exited.`

**Comment by isovic** [comment]
Hi,
hmm this is a bit strange.
Are you perhaps running it on a 32-bit architecture?

Best regards,
Ivan.

**Comment by fg6** [comment]
Hi,
no, using 64bit.

Just checked more closely the consensus from when using the  example2-paf-pipe-lambda.sh as template script, and it is identical to the initial contigs from miniasm.

Thanks,
Francesca

**Comment by isovic** [comment]
Hi Francesca,

Would it be possible for you to tell me which exact model of the CPU you are using?
Also, are you running a VM or bare metal?
And, have you by any chance compiled racon on another machine and just copied it to the one you're getting this error, or have you built it on the spot?

This info might help resolve the issue,
Best regards,
Ivan.

**Comment by fg6** [comment]
Hi Ivan,
thanks for the comment, yes you're right I compiled it on a different machine from the one I was trying to use it.
I was compiling on a  AMD Opteron(TM) Processor 6272 and using it on a Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz.
Thanks a lot!
Francesca

**Comment by isovic** [comment]
Interesting combination - but I don't think we can reproduce your setup here...
Could you by any chance try recompiling on the target system and report back if it works?

Best regards,
Ivan.

**Comment by fg6** [comment]
Hi,
yes, I did that, and now it works fine.. weird though..

Thank you!
Francesca

**Comment by isovic** [comment]
That's great to hear, thanks! :-)
I guess the instruction set between the CPUs is a bit different - we never had problems copying the binary from an Intel to another Intel, as long as the OSs were compatible.

Best regards,
Ivan.
