### ISSUE TITLE
minimal reporting through stderr

### ISSUE THREAD

**Issue by leleory** [isovic/racon#102]
Hello there,
When I run racon in a cluster environment (SGE) I store the STDERR in the log file to see if the run went OK.
This is very useful to identify failed runs. Nevertheless due to the way racon reports it's progress the logfile (especially on bigger datasets) reaches sever GB. This is not just a storage issue, but also takes a long time to skim through the report. Can the code be enhanced, so that detailed progress is not reported, but errors would still come through? If there would be a parameter to specify minimal reporting that would be really useful.
Thank you,
Lel

**Comment by rvaser** [comment]
Hi Lel,
I already have this problem reported before but did not have the time yet to update. Will do it in next couple of days.

Best regards,
Robert

**Comment by leleory** [comment]
That is great, thanks Robert. Looking forward to it.

Lel

**Comment by rvaser** [comment]
Implemented in latest commit (`v1.3.3`).

**Comment by leleory** [comment]
Hi Robert,
It works great, thanks very much for the improvement!
Lel
