### ISSUE TITLE
Racon won't execute

### ISSUE THREAD

**Issue by peflanag** [isovic/racon#106]
Hi,

I installed Racon so I can run Unicycler. But when I run Unicycler the error that comes back is that Racon is not available. I think its because it doesn't know its destination but I do not have the knowledge to add scripts to paths. I'm very much a novice.

Any help would be great!

**Comment by rvaser** [comment]
Hello,
try running `make install` from your build folder.

Best regards,
Robert

**Comment by peflanag** [comment]
Hi Robert,

Thanks for that I have it working now!
