### ISSUE TITLE
Crashes when SAM input file is used.

### ISSUE THREAD

**Issue by joshualoving** [isovic/racon#11]
Instead of a PAF file, I'm giving racon a SAM file output by graphmap. It crashes with the following error: 

```
Using PAF for input alignments. (graphmap.sam)

[13:26:30 main] Loading reads.
[13:26:33 main] Hashing qnames.
[13:26:33 main] Parsing the overlaps file.
[13:26:33 main] Unique overlaps will be filtered on the fly.
[Mon, 09 Jan 17 18:26:33 +0000 ERROR] #5: Unexpected value found! Overlaps are not formatted in the PAF format. Exiting.In function: 'ParsePAF'.

[Mon, 09 Jan 17 18:26:33 +0000 ERROR] #5: Unexpected value found! Overlaps are not formatted in the PAF format. Exiting.In function: 'ParsePAF'.
Exiting.
```

Is there a command line option that I'm missing?

Thanks

**Comment by joshualoving** [comment]
I read through the code and found that the `--sam` flag is required for sam files. I didn't see this in the help text or manual. Thanks, please close!

**Comment by isovic** [comment]
Hi Joshua,
Thank you for the issue! I updated the README to mention this right at the beginning.

Best regards,
Ivan.
