### ISSUE TITLE
I want to compile Racon on ARM platform

### ISSUE THREAD

**Issue by yinyixiao** [isovic/racon#112]
when i make it , there are a error    "/root/racon/vendor/thread_pool/src/thread_pool.cpp:1:0: error: unknown value 'native' for -march"
How to solve it?

**Comment by rvaser** [comment]
Hi,
try removing `-march=native` from `vendor/thread_pool/CMakeLists.txt`. Afterwards if it still is not working, you can try and replace `-march=native` in root `CMakeLists.txt` with `-msse4.1`.

Best regards,
Robert
