### ISSUE TITLE
Unpolished bases as lower case

### ISSUE THREAD

**Issue by mrvollger** [isovic/racon#117]
Just a suggesting an enhancement. 

When using `-u` it would be nice if unpolished bases were lowercase. 

Best,
Mitchell

**Comment by rvaser** [comment]
Hi Mitchell,
are you suggesting that the bases of unpolished sequences (sequences outputted when using `-u`) are all lowercase or would you like to have lowercase bases in both polished and unpolished sequences?

Sorry for the late response!
Best regards,
Robert

**Comment by mvollger** [comment]
Hi Robert, 

I was suggesting that when `-u` is used that unpolished bases are lowercase, and polished bases are uppercase, or perhaps a new flag with this behavior. If it helps convince you this is the defualt now used by the PacBio polishers https://github.com/PacificBiosciences/GenomicConsensus/blob/develop/doc/FAQ.rst#what-does-it-mean-that-quiver-consensus-is-de-novo. It is not a big deal, but it is helpful in downstream analysis to be able to make separate quality scores for polished and unpolished bases, and lower/upper case makes that distinction easy. 

No worries. 

Best,
Mitchell
