### ISSUE TITLE
CR in log output

### ISSUE THREAD

**Issue by ptrebert** [isovic/racon#120]
Hi,
I executed Racon v1.3.2 (see my comment in #119) and sent stderr to a log file. I noticed that the series of `aligned overlap xyz` messages is not separated by `\n`, i.e., 

![racon_cr](https://user-images.githubusercontent.com/36245614/57838186-8169ca00-77c4-11e9-836b-20c1e8f4b8a2.png)
 
Running `tr '\r' '\n'` on the file fixes that, but it would be more convenient if the messages were separated by `\n`. Thanks.
Best,
Peter

**Comment by rvaser** [comment]
Hi Peter,
the newest version has a much smaller log with a progress bar. Although, it is still using `\r` for a prettier console log.

Best regards,
Robert

**Comment by ptrebert** [comment]
Any timeline for the release of this new version?

**Comment by rvaser** [comment]
For now you can just download the latest commit directly from github. I'll try to make a new release one I refactor some of the submodules racon is using.

**Comment by ptrebert** [comment]
Allright, thanks for the info.

**Comment by rvaser** [comment]
@ptrebert `v1.3.3` has been released.

**Comment by ptrebert** [comment]
@rvaser Awesome, thanks for the update!
