### ISSUE TITLE
Racon output missing

### ISSUE THREAD

**Issue by mradz19** [isovic/racon#124]
I'm new to using racon and have managed to get it working to polish a draft assembly with nanopore reads. However I caanot find the output file from racon, nothing is generated in the directory I run racon from.

Does racon output polished contigs in a different directory?

**Comment by rvaser** [comment]
Hi Michael,
racon outputs polished sequences to stdout so you have to pipe your command to a file like bellow:
```bash
racon -t 12 reads.fasta overlaps.paf assembly.fasta > polished_assembly.fasta
```

Best regards,
Robert

**Comment by mradz19** [comment]
Hi @rvaser 

Thanks for the prompt reply and the easy fix!
