### ISSUE TITLE
-qv or -bq in the README?

### ISSUE THREAD

**Issue by jts** [isovic/racon#13]
Hi,

In the README it says:

"There is also a default QV threshold set to 10 (Phred score). If your data is of poorer quality, you can modify this parameter using `--qv FLOAT`"

I think this should be `-bq FLOAT`?

**Comment by isovic** [comment]
Hi Jared,
thanks, good catch! The actual parameter is ```--bq```, the README was wrong.
I updated it now.

Best regards,
Ivan.
