### ISSUE TITLE
error will installation with cuda enabled

### ISSUE THREAD

**Issue by michieitel** [isovic/racon#131]
Hi!

I am trying to install Racon v 1.4.2 with CUDA (10.1) enabled but it throws an error during make (below). Can you please help to identify the issue.

Thanks
Michael

cmake (v. 3.10.2) ran without error 
`cmake -DCMAKE_BUILD_TYPE=Release -Dracon_enable_cuda=ON -Dracon_build_tests=ON ..
`
> -- The C compiler identification is GNU 7.4.0
> -- The CXX compiler identification is GNU 7.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Using CUDA 10.1 from /usr/local/cuda
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of off64_t
> -- Check size of off64_t - done
> -- Looking for fseeko
> -- Looking for fseeko - found
> -- Looking for unistd.h
> -- Looking for unistd.h - found
> -- Renaming
> --     /home/ubuntu/racon/vendor/bioparser/vendor/zlib/zconf.h
> -- to 'zconf.h.included' because this file is included with zlib
> -- but CMake generates it automatically in the build directory.
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> Setting warning flags
> -- Build type: Release
> -- Using CUDA 10.1 from /usr/local/cuda
> -- Using CUDA 10.1 from /usr/local/cuda
> -- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
> -- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/ubuntu/racon/build

running make resulted in an error:
> Scanning dependencies of target spoa
> Scanning dependencies of target logging
> Scanning dependencies of target gtest
> Scanning dependencies of target thread_pool
> Scanning dependencies of target zlibstatic
> Scanning dependencies of target edlib_static
> Scanning dependencies of target logger
> [  3%] Building CXX object vendor/thread_pool/CMakeFiles/thread_pool.dir/src/thread_pool.cpp.o
> [  6%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/sisd_alignment_engine.cpp.o
> [ 10%] Building CXX object ClaraGenomicsAnalysis/common/logging/CMakeFiles/logging.dir/src/logging.cpp.o
> [ 13%] Building CXX object vendor/edlib/CMakeFiles/edlib_static.dir/edlib/src/edlib.cpp.o
> [ 13%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
> [ 16%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/graph.cpp.o
> [ 16%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/simd_alignment_engine.cpp.o
> [ 20%] Building CXX object vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o
> [ 23%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/crc32.o
> [ 23%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/deflate.o
> [ 23%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/inflate.o
> [ 26%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/gzwrite.o
> [ 30%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/infback.o
> [ 30%] Building CXX object vendor/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> [ 30%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/compress.o
> [ 33%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/adler32.o
> [ 36%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/gzclose.o
> [ 36%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/gzread.o
> [ 36%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/gzlib.o
> [ 36%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/inftrees.o
> [ 40%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/inffast.o
> [ 40%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/trees.o
> [ 43%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/uncompr.o
> [ 43%] Building C object vendor/bioparser/vendor/zlib/CMakeFiles/zlibstatic.dir/zutil.o
> [ 43%] Linking CXX static library lib/liblogger.a
> [ 43%] Built target logger
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:313:30: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>      std::unique_ptr<__mxxxi[]> sequence_profile_storage;
>                               ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:318:30: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>      std::unique_ptr<__mxxxi[]> M_storage;
>                               ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:322:30: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>      std::unique_ptr<__mxxxi[]> masks_storage;
>                               ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:326:30: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>      std::unique_ptr<__mxxxi[]> penalties_storage;
>                               ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp: In member function ‘void spoa::SimdAlignmentEngine::realloc(uint32_t, uint32_t, uint32_t)’:
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:386:69: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>          pimpl_->sequence_profile_storage = std::unique_ptr<__mxxxi[]>(storage);
>                                                                      ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:397:54: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>          pimpl_->M_storage = std::unique_ptr<__mxxxi[]>(storage);
>                                                       ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:405:58: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>          pimpl_->masks_storage = std::unique_ptr<__mxxxi[]>(storage);
>                                                           ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:413:62: warning: ignoring attributes on template argument ‘spoa::__mxxxi [] {aka __vector(4) long long int []}’ [-Wignored-attributes]
>          pimpl_->penalties_storage = std::unique_ptr<__mxxxi[]>(storage);
>                                                               ^
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp: In instantiation of ‘T* spoa::allocateAlignedMemory(T**, uint32_t, uint32_t) [with T = __vector(4) long long int; uint32_t = unsigned int]’:
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:384:61:   required from here
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:36:16: warning: ‘new’ of type ‘__vector(4) long long int’ with extended alignment 32 [-Waligned-new=]
>      *storage = new T[size + alignment - 1];
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:36:16: note: uses ‘void* operator new [](std::size_t)’, which does not have an alignment parameter
> /home/ubuntu/racon/vendor/spoa/src/simd_alignment_engine.cpp:36:16: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
> [ 46%] Linking C static library ../../lib/libz.a
> [ 46%] Built target zlibstatic
> [ 46%] Linking CXX static library lib/libthread_pool.a
> [ 46%] Built target thread_pool
> [ 46%] Linking CXX static library ../../lib/libedlib_static.a
> [ 46%] Built target edlib_static
> [ 46%] Linking CXX static library lib/libspoa.a
> [ 46%] Built target spoa
> [ 50%] Linking CXX static library ../../../lib/libgtest.a
> [ 50%] Linking CXX static library ../../../lib/liblogging.a
> [ 50%] Built target gtest
> Scanning dependencies of target gtest_main
> [ 50%] Building CXX object vendor/googletest/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
> [ 50%] Built target logging
> [ 50%] Building NVCC (Device) object ClaraGenomicsAnalysis/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner_generated_ukkonen_gpu.cu.o
> [ 53%] Building NVCC (Device) object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa_generated_cudapoa_nw_banded.cu.o
> [ 53%] Building NVCC (Device) object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa_generated_cudapoa_kernels.cu.o
> [ 53%] Building NVCC (Device) object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa_generated_cudapoa_nw.cu.o
> [ 56%] Building NVCC (Device) object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa_generated_cudapoa_topsort.cu.o
> [ 56%] Building NVCC (Device) object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa_generated_cudapoa_add_alignment.cu.o
> [ 56%] Linking CXX static library ../../../lib/libgtest_main.a
> [ 56%] Built target gtest_main
> Scanning dependencies of target cudaaligner
> [ 60%] Building CXX object ClaraGenomicsAnalysis/cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner.cpp.o
> [ 60%] Building CXX object ClaraGenomicsAnalysis/cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner.cpp.o
> [ 63%] Building CXX object ClaraGenomicsAnalysis/cudaaligner/CMakeFiles/cudaaligner.dir/src/alignment_impl.cpp.o
> [ 63%] Building CXX object ClaraGenomicsAnalysis/cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner_global.cpp.o
> Scanning dependencies of target cudapoa
> [ 63%] Building CXX object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa.cpp.o
> [ 66%] Building CXX object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/batch.cpp.o
> [ 66%] Building CXX object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa_batch.cpp.o
> [ 70%] Building CXX object ClaraGenomicsAnalysis/cudapoa/CMakeFiles/cudapoa.dir/src/allocate_block.cpp.o
> [ 73%] Linking CXX static library ../../lib/libcudaaligner.a
> [ 73%] Built target cudaaligner
> [ 73%] Linking CXX static library ../../lib/libcudapoa.a
> [ 73%] Built target cudapoa
> Scanning dependencies of target racon_test
> Scanning dependencies of target racon
> [ 73%] Building CXX object CMakeFiles/racon.dir/src/cuda/cudabatch.cpp.o
> [ 76%] Building CXX object CMakeFiles/racon.dir/src/cuda/cudaaligner.cpp.o
> [ 76%] Building CXX object CMakeFiles/racon_test.dir/test/racon_test.cpp.o
> [ 80%] Building CXX object CMakeFiles/racon.dir/src/cuda/cudapolisher.cpp.o
> [ 80%] Building CXX object CMakeFiles/racon.dir/src/main.cpp.o
> [ 83%] Building CXX object CMakeFiles/racon_test.dir/src/polisher.cpp.o
> [ 83%] Building CXX object CMakeFiles/racon_test.dir/src/overlap.cpp.o
> [ 83%] Building CXX object CMakeFiles/racon.dir/src/overlap.cpp.o
> [ 86%] Building CXX object CMakeFiles/racon_test.dir/src/sequence.cpp.o
> [ 86%] Building CXX object CMakeFiles/racon_test.dir/src/window.cpp.o
> [ 86%] Building CXX object CMakeFiles/racon.dir/src/window.cpp.o
> [ 90%] Building CXX object CMakeFiles/racon.dir/src/sequence.cpp.o
> [ 93%] Building CXX object CMakeFiles/racon.dir/src/polisher.cpp.o
> [ 93%] Building CXX object CMakeFiles/racon_test.dir/src/cuda/cudabatch.cpp.o
> [ 96%] Building CXX object CMakeFiles/racon_test.dir/src/cuda/cudaaligner.cpp.o
> [100%] Building CXX object CMakeFiles/racon_test.dir/src/cuda/cudapolisher.cpp.o
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In member function ‘virtual void racon::CUDAPolisher::find_overlap_breaking_points(std::vector<std::unique_ptr<racon::Overlap> >&)’:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:96:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log();
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In member function ‘virtual void racon::CUDAPolisher::find_overlap_breaking_points(std::vector<std::unique_ptr<racon::Overlap> >&)’:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:96:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log();
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In lambda function:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:150:36: error: invalid use of incomplete type ‘class logger::Logger’
>                              logger_->bar("[racon::CUDAPolisher::initialize] aligning overlaps");
>                                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In lambda function:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:150:36: error: invalid use of incomplete type ‘class logger::Logger’
>                              logger_->bar("[racon::CUDAPolisher::initialize] aligning overlaps");
>                                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In member function ‘virtual void racon::CUDAPolisher::polish(std::vector<std::unique_ptr<racon::Sequence> >&, bool)’:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:219:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log("[racon::CUDAPolisher::polish] allocated memory on GPUs");
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:260:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log();
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In lambda function:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:297:36: error: invalid use of incomplete type ‘class logger::Logger’
>                              logger_->bar("[racon::CUDAPolisher::polish] generating consensus");
>                                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In member function ‘virtual void racon::CUDAPolisher::polish(std::vector<std::unique_ptr<racon::Sequence> >&, bool)’:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:327:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log("[racon::CUDAPolisher::polish] polished windows on GPU");
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:330:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log();
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In member function ‘virtual void racon::CUDAPolisher::polish(std::vector<std::unique_ptr<racon::Sequence> >&, bool)’:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:219:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log("[racon::CUDAPolisher::polish] allocated memory on GPUs");
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:260:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log();
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:356:20: error: invalid use of incomplete type ‘class logger::Logger’
>              logger_->log("[racon::CUDAPolisher::polish] polished remaining windows on CPU");
>                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:357:20: error: invalid use of incomplete type ‘class logger::Logger’
>              logger_->log();
>                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In lambda function:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:297:36: error: invalid use of incomplete type ‘class logger::Logger’
>                              logger_->bar("[racon::CUDAPolisher::polish] generating consensus");
>                                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp: In member function ‘virtual void racon::CUDAPolisher::polish(std::vector<std::unique_ptr<racon::Sequence> >&, bool)’:
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:327:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log("[racon::CUDAPolisher::polish] polished windows on GPU");
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:330:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log();
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:388:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log("[racon::CUDAPolisher::polish] generated consensus");
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:356:20: error: invalid use of incomplete type ‘class logger::Logger’
>              logger_->log("[racon::CUDAPolisher::polish] polished remaining windows on CPU");
>                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:357:20: error: invalid use of incomplete type ‘class logger::Logger’
>              logger_->log();
>                     ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> /home/ubuntu/racon/src/cuda/cudapolisher.cpp:388:16: error: invalid use of incomplete type ‘class logger::Logger’
>          logger_->log("[racon::CUDAPolisher::polish] generated consensus");
>                 ^~
> In file included from /home/ubuntu/racon/src/cuda/cudapolisher.hpp:11:0,
>                  from /home/ubuntu/racon/src/cuda/cudapolisher.cpp:13:
> /home/ubuntu/racon/src/polisher.hpp:29:11: note: forward declaration of ‘class logger::Logger’
>      class Logger;
>            ^~~~~~
> CMakeFiles/racon.dir/build.make:182: recipe for target 'CMakeFiles/racon.dir/src/cuda/cudapolisher.cpp.o' failed
> make[2]: *** [CMakeFiles/racon.dir/src/cuda/cudapolisher.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/racon_test.dir/build.make:182: recipe for target 'CMakeFiles/racon_test.dir/src/cuda/cudapolisher.cpp.o' failed
> make[2]: *** [CMakeFiles/racon_test.dir/src/cuda/cudapolisher.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:120: recipe for target 'CMakeFiles/racon_test.dir/all' failed
> make[1]: *** [CMakeFiles/racon_test.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/racon.dir/all' failed
> make[1]: *** [CMakeFiles/racon.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by rvaser** [comment]
Hi Michael,
I was refactoring without a valid nvcc compiler, I hope I fixed it in the latest commit. Could you please verify that?

Best regards,
Robert

**Comment by michieitel** [comment]
Fixed. Compilation work!
Thanks a lot for that incredibly fast fix!
Michael
