### ISSUE TITLE
cuda usage

### ISSUE THREAD

**Issue by michieitel** [isovic/racon#133]
Hi!

Any recommendations on how to use the cuda options?

> -c, --cudapoa-batches
>         default: 1
>         number of batches for CUDA accelerated polishing
>     -b, --cuda-banded-alignment
>         use banding approximation for polishing on GPU. Only applicable when -c is used.
>     --cudaaligner-batches (experimental)
>         Number of batches for CUDA accelerated alignment

How can I identify suitable settings for my GPU?

thanks
Michael

**Comment by rvaser** [comment]
Hi Michael,
I think that each batch is around 200MB, the more batches the faster it will run. Just divide your GPU memory in MB with 200 and round down. For further speed-up, you can use the option `-b` which might have a tiny bit of accuracy loss.

Best regards,
Robert

**Comment by michieitel** [comment]
I see! Thanks for this information!

Any guess when you manage to implement short read polishing with cuda? That would be amazing!!

Best
Michael

**Comment by rvaser** [comment]
You can ask the peeps from Nvidia @ https://github.com/clara-genomics/ClaraGenomicsAnalysis :)

Best regards,
Robert

**Comment by michieitel** [comment]
Ah I see ;-)
