### ISSUE TITLE
Please support .fna as file extension for the contigs

### ISSUE THREAD

**Issue by claczny** [isovic/racon#136]
Hi,

could you please add support for `.fna` file extensions?
I find that it helps to disambiguate whether there are nucleic acid or amino acid sequences in the file.

Thank you.

Best,

Cedric

**Comment by rvaser** [comment]
Available in version `1.4.6` at https://github.com/lbcb-sci/racon. Sorry for waiting.

Best regards,
Robert

**Comment by claczny** [comment]
@rvaser Great, thank you! No need to be sorry, it is only two weeks and this is clearly a minor issue :)
