### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by MichelMoser** [isovic/racon#137]
Hi, 

I get a segmentaton fault when running racon on a 2 TB RAM machine. 
Unfortunately, there is no more messages showing...

command:
```racon  -t 16 -m 8 -x -6 -g -8 -w 500 -u reads.fastq.gz  reads_2_assembly.sam.gz  assembly.fasta 
[racon::Polisher::initialize] loaded target sequences 4.484466 s                                
[racon::Polisher::initialize] loaded sequences 638.382458 s               
Segmentation fault             
```                      
I am using racon: v1.4.4. 

Dataset sizes: 
reads: 27 GB
assembly: 800 MB
overlaps: 28 GB

Any ideas how to resolve the issue?

**Comment by rvaser** [comment]
Hello,
which format is your overlaps file?

Best regards,
Robert

**Comment by rvaser** [comment]
I think I found the problem, will update racon soon.

**Comment by rvaser** [comment]
Please try out `v1.4.5` at https://github.com/lbcb-sci/racon.

**Comment by MichelMoser** [comment]
thanks, works now
