### ISSUE TITLE
samscripts make error

### ISSUE THREAD

**Issue by freddymonteiro** [isovic/racon#14]
Hi all,
I get the following error during `make modules`
```
fatal: reference is not a tree: 8225661d48e8c341dc46f880bdf5d02c37cc6adf
Unable to checkout '8225661d48e8c341dc46f880bdf5d02c37cc6adf' in submodule path 'codebase/samscripts'
Makefile:49: recipe for target 'modules' failed
make: *** [modules] Error 1
```
`module tools` and `module -j` run smoothly
Examples also run without errors.

My distribution details:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```
All dependencies installed.

Thank you in advance,
Freddy

**Comment by rvaser** [comment]
Hello Freddy,

the issue has been fixed. Please do a fresh clone and install.

Best regards,
Robert
