### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by Tdanis** [isovic/racon#144]
Hello, I am trying this command with racon:

racon -m 8 -x -6 -g -8 -w 500 -t 20 -u unpolished.fasta /home1/tdanis/Porechop/porechoped.fastq /home/Minimap2-mapping/mapping.sam /home/tdanis/porechoped.fasta  > polished.fasta

**and the output error is:**

terminate called after throwing an instance of 'std::invalid_argument'
  what():  [bioparser::createParser] error: unable to open file unpolished.fasta!
Aborted

Thank you for your help

**Comment by rvaser** [comment]
Hello,
option `-u` does not require an argument, it just prints unpolished contigs alongside polished ones to stdout. You can find them by searching for headers that have "XC:f:0.0000", which means that not a single window was polished of that sequence. The correct command is the following:
```bash
racon -u -m 8 -x -6 -g -8 -w 500 -t 20 /home1/tdanis/Porechop/porechoped.fastq /home/Minimap2-mapping/mapping.sam /home/tdanis/porechoped.fasta > polished.fasta
```

Best regads,
Robert

**Comment by Tdanis** [comment]
Thank you so  much for your help. 
I want to ask something another one, so is it a good strategy to 'map back' all these unpolished sequences and after that to implement again medaka second time?

**Comment by rvaser** [comment]
I am not sure what exactly you are asking. From the Medaka github page, it is advised to run 4 iterations of Racon, meaning you will have to map the reads 4 times and invoke Racon after each iteration. Then you run Medaka. If you are asking something else, please clarify :)

**Comment by Tdanis** [comment]
Ok firstly sorry, I mean to map not only the trimmed or raw-basecall reads but also the unpolished seqs of the last round of racon. For example, 3 times racon with mapping of the reads to draft assembly and at the last time mapping of upolished reads of racon instead of raw reads and then medaka.

**Comment by rvaser** [comment]
I am not sure if that will yield any benefits. You can certainly try!
