### ISSUE TITLE
[bioparser::FastaParser] error: invalid file format!

### ISSUE THREAD

**Issue by astulaaa** [isovic/racon#145]
Hello, I was running minimap2 followed by racon, while minimap seems to work properly its output does not seem to be recognized by racon. The command line as follows:

 minimap2 -t 31 -x map-ont  s_reads3.srp.fa ../../Resources/raw.combined.fa > ula.mapping_1st.paf
racon -t 31 -m 8 -x -6 -g -8 -w 500 ../../Resources/raw.combined.fa ula.mapping_1st.paf  s_reads3.srp.fa > ula.racon_1st.fa

log file comes with a message like this: terminate called after throwing an instance of 'std::invalid_argument'
  what():  [bioparser::FastaParser] error: invalid file format!
/var/spool/gridengine/execd/job_scripts/213619: line 10: 92317 Aborted
What could be the problem and with which input file? Also most of the same files were utilized by minimap2 so they are unlikely to be damaged
thank you

**Comment by rvaser** [comment]
Hello,
which Racon version are you using? There is maybe something unusual in either of your fasta files, or there is a bug in the parser.

Best regards,
Robert

**Comment by astulaaa** [comment]
racon version v1.4.7
Thanks

**Comment by rvaser** [comment]
Can you check if there is an empty sequence in either of the fasta files?

**Comment by astulaaa** [comment]
I have found the issue, wrong input file. Thanks!
