### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pulichandramoulireddy** [isovic/racon#153]
Hi, I am trying to install racon on centos 6.10, cmake version 3.6.2, gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23) but the following error is popping. Can anyone suggest a solution? Thank you!

[ 3%] Building CXX object vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o
In file included from /root/racon/vendor/logger/src/logger.cpp:9:
/root/racon/vendor/logger/include/logger/logger.hpp:24: error: ‘logger::Logger::Logger(logger::Logger&&)’ cannot be defaulted
/root/racon/vendor/logger/include/logger/logger.hpp:25: error: ‘logger::Logger& logger::Logger::operator=(logger::Logger&&)’ cannot be defaulted
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: template argument 1 is invalid
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: template argument 2 is invalid
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::log()’:
/root/racon/vendor/logger/src/logger.cpp:21: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp:21: error: unable to deduce ‘auto’ from ‘’
/root/racon/vendor/logger/src/logger.cpp:22: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/src/logger.cpp:22: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/src/logger.cpp:22: error: template argument 1 is invalid
/root/racon/vendor/logger/src/logger.cpp:22: error: template argument 2 is invalid
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::log(const std::string&) const’:
/root/racon/vendor/logger/src/logger.cpp:30: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::bar(const std::string&)’:
/root/racon/vendor/logger/src/logger.cpp:39: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::total(const std::string&) const’:
/root/racon/vendor/logger/src/logger.cpp:52: error: ‘std::chrono::steady_clock’ has not been declared
make[2]: *** [vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o] Error 1
make[1]: *** [vendor/logger/CMakeFiles/logger.dir/all] Error 2
make: *** [all] Error 2

**Comment by rvaser** [comment]
Hello,
the minimal required gcc version is 4.8.

Best regards,
Robert

**Comment by pulichandramoulireddy** [comment]
Thank you! Robert, 
I realised it after posting I am upgrading gcc.

**Comment by pulichandramoulireddy** [comment]
I have updated to gcc (GCC) 5.1.0 and rebuild and try to install it again. I am facing the same error.
make is throwing following error. 
Scanning dependencies of target logger
[  3%] Building CXX object vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o
In file included from /root/racon/vendor/logger/src/logger.cpp:9:
/root/racon/vendor/logger/include/logger/logger.hpp:24: error: ‘logger::Logger::Logger(logger::Logger&&)’ cannot be defaulted
/root/racon/vendor/logger/include/logger/logger.hpp:25: error: ‘logger::Logger& logger::Logger::operator=(logger::Logger&&)’ cannot be defaulted
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: template argument 1 is invalid
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: template argument 2 is invalid
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::log()’:
/root/racon/vendor/logger/src/logger.cpp:21: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp:21: error: unable to deduce ‘auto’ from ‘<expression error>’
/root/racon/vendor/logger/src/logger.cpp:22: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/src/logger.cpp:22: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/src/logger.cpp:22: error: template argument 1 is invalid
/root/racon/vendor/logger/src/logger.cpp:22: error: template argument 2 is invalid
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::log(const std::string&) const’:
/root/racon/vendor/logger/src/logger.cpp:30: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::bar(const std::string&)’:
/root/racon/vendor/logger/src/logger.cpp:39: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::total(const std::string&) const’:
/root/racon/vendor/logger/src/logger.cpp:52: error: ‘std::chrono::steady_clock’ has not been declared
make[2]: *** [vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o] Error 1
make[1]: *** [vendor/logger/CMakeFiles/logger.dir/all] Error 2
make: *** [all] Error 2

**Comment by rvaser** [comment]
Please paste the output of `make VERBOSE=1`. I suspect that cmake did not pick up the updated compiler.

**Comment by pulichandramoulireddy** [comment]
This is the output

/usr/local/bin/cmake -H/root/racon -B/root/racon/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /root/racon/build/CMakeFiles /root/racon/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/root/racon/build'
make -f vendor/logger/CMakeFiles/logger.dir/build.make vendor/logger/CMakeFiles/logger.dir/depend
make[2]: Entering directory `/root/racon/build'
cd /root/racon/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /root/racon /root/racon/vendor/logger /root/racon/build /root/racon/build/vendor/logger /root/racon/build/vendor/logger/CMakeFiles/logger.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/root/racon/build'
make -f vendor/logger/CMakeFiles/logger.dir/build.make vendor/logger/CMakeFiles/logger.dir/build
make[2]: Entering directory `/root/racon/build'
[  3%] Building CXX object vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o
cd /root/racon/build/vendor/logger && /usr/bin/c++    -I/root/racon/src -I/root/racon/vendor/logger/include  -Wall -Wextra -pedantic -Wall -Wextra -pedantic -O3 -DNDEBUG   -std=c++0x -o CMakeFiles/logger.dir/src/logger.cpp.o -c /root/racon/vendor/logger/src/logger.cpp
In file included from /root/racon/vendor/logger/src/logger.cpp:9:
/root/racon/vendor/logger/include/logger/logger.hpp:24: error: ‘logger::Logger::Logger(logger::Logger&&)’ cannot be defaulted
/root/racon/vendor/logger/include/logger/logger.hpp:25: error: ‘logger::Logger& logger::Logger::operator=(logger::Logger&&)’ cannot be defaulted
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: template argument 1 is invalid
/root/racon/vendor/logger/include/logger/logger.hpp:53: error: template argument 2 is invalid
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::log()’:
/root/racon/vendor/logger/src/logger.cpp:21: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp:21: error: unable to deduce ‘auto’ from ‘<expression error>’
/root/racon/vendor/logger/src/logger.cpp:22: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/src/logger.cpp:22: error: ‘steady_clock’ is not a member of ‘std::chrono’
/root/racon/vendor/logger/src/logger.cpp:22: error: template argument 1 is invalid
/root/racon/vendor/logger/src/logger.cpp:22: error: template argument 2 is invalid
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::log(const std::string&) const’:
/root/racon/vendor/logger/src/logger.cpp:30: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::bar(const std::string&)’:
/root/racon/vendor/logger/src/logger.cpp:39: error: ‘std::chrono::steady_clock’ has not been declared
/root/racon/vendor/logger/src/logger.cpp: In member function ‘void logger::Logger::total(const std::string&) const’:
/root/racon/vendor/logger/src/logger.cpp:52: error: ‘std::chrono::steady_clock’ has not been declared
make[2]: *** [vendor/logger/CMakeFiles/logger.dir/src/logger.cpp.o] Error 1
make[2]: Leaving directory `/root/racon/build'
make[1]: *** [vendor/logger/CMakeFiles/logger.dir/all] Error 2
make[1]: Leaving directory `/root/racon/build'
make: *** [all] Error 2

**Comment by rvaser** [comment]
What do you get when you run `/usr/bin/c++ --version`?

**Comment by pulichandramoulireddy** [comment]
c++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

**Comment by rvaser** [comment]
Try to find the path to your new compiler version and run `CC=<path to gcc5.1> CXX=<path to g++5.1> cmake -DCMAKE_BUILD_TYPE=Release ..`

**Comment by pulichandramoulireddy** [comment]
I tried CC=/usr/local/bin/gcc CXX=/usr/local/bin/g++ cmake -DCMAKE_BUILD_TYPE=Release ..
but throwing same error again

**Comment by rvaser** [comment]
Does `make VERBOSE=1` have the same output? The line of interest is:

`cd /root/racon/build/vendor/logger && /usr/bin/c++ -I/root/racon/src -I/root/racon/vendor/logger/include -Wall -Wextra -pedantic -Wall -Wextra -pedantic -O3 -DNDEBUG -std=c++0x -o`

**Comment by pulichandramoulireddy** [comment]
It appears problem solved. I have romoved the build directory and did build again using CC=/usr/local/bin/gcc CXX=/usr/local/bin/g++ cmake -DCMAKE_BUILD_TYPE=Release ..

Thank you!

**Comment by rvaser** [comment]
Great to hear! :)
