### ISSUE TITLE
Question for polishing 

### ISSUE THREAD

**Issue by Tdanis** [isovic/racon#154]
Hello again, 

I have got one question about assembly-polishing pipeline. I am going to use racon after assembly construction. So could you help me which one command have I to use with minimap2? 
**map-ont** or **ava-ont** (my dataset is Nanopore)

Thank you for your help

**Comment by rvaser** [comment]
Hi again,
if you want to polish the assembly, you need to pass `-x map-ont` to `minimap2`. If you want to error correct your reads with each other, pass `-x ava-ont`.

Best regards,
Robert
