### ISSUE TITLE
Release on Github

### ISSUE THREAD

**Issue by mictadlo** [isovic/racon#16]
Hi,
Could you please produce a release on Github, because I started to create [Bioconda](https://github.com/bioconda/bioconda-recipes) package and in my understanding `make modules` is not supported?

Thank you in advance,

Michal

**Comment by isovic** [comment]
Hi Michal,

we packaged a release now, you can find it here:  
https://github.com/isovic/racon/releases/tag/0.5.0

Please note: download the file that I manually uploaded, not the official GitHub link, because GitHub does not package submodules automatically.

Hope this helps.

Best regards,
Ivan.
