### ISSUE TITLE
wrapperscript cudaaligner problems

### ISSUE THREAD

**Issue by Colorstorm** [isovic/racon#161]
Hi,

I have problems with the racon wrapper script and using racon NOT on a gpu.

The error is: `racon: unrecognized option '--cudaaligner-batches'`

The racon version is v1.4.13
```
racon_wrapper --split 2500 -t 16 -u test.reads.fastq test.ovl.paf test.fasta > wrapper_test.fasta
[RaconWrapper::run] preparing data with rampler
[RaconWrapper::run] total number of splits: 3841
[RaconWrapper::run] processing data with racon
/path/racon: unrecognized option '--cudaaligner-batches'
```
Thanks,
Fabian

**Comment by rvaser** [comment]
Hello Fabian,
this issue has been already fixed in commit https://github.com/lbcb-sci/racon/commit/31a3c92878d19a9ef31462193e6a7862e6fe1611 which is version `1.4.16`. I did not publish a release yet.

Best regards,
Robert

**Comment by Colorstorm** [comment]
Hi Robert,

Thanks a lot, then I will update it via git.

Cheers,
Fabian
