### ISSUE TITLE
what():  [bioparser::PafParser] error: invalid file format!

### ISSUE THREAD

**Issue by fengyuanli304** [isovic/racon#163]
Hi, I have a problem with Racon. 

Firstly, I got the .paf with minimap2.
minimap2 -t 16 -ax map-pb /home/lfy/genome/pacbio/rawdata/preseven.ctg.fa /home/lfy/genome/pacbio/rawdata/merge1.fastq > /home/lfy/genome/pacbio/minimap2/1/round1_1.paf
Then, I used the folllowing command to run Racon
/racon/build/bin/racon_wrapper -t 16 /home/lfy/genome/pacbio/rawdata/merge1.fastq /home/lfy/genome/pacbio/minimap2/1/round1_1.paf /home/lfy/genome/pacbio/rawdata/preseven.ctg.fa --subsample 3942657983 50 > racon1_1.fasta 

I got the error message"[RaconWrapper::run] preparing data with rampler
[RaconWrapper::run] processing data with racon
[racon::Polisher::initialize] loaded target sequences 37.596671 s
[racon::Polisher::initialize] loaded sequences 20.070395 s
terminate called after throwing an instance of 'std::invalid_argument'
  what():  [bioparser::PafParser] error: invalid file format!"
The version of Racon is v.1.4.13
Please give me some advises. Thank you.

P.S. I have used a small file (zcat merge.fastq.gz | head -n 1000 > small.fastq) to run minimap2 + Racon (3 rounds) and it is succeed.

Best wishes,
Fengyuan

**Comment by rvaser** [comment]
Hi Fengyuan,
option `-a` of minimap produces a SAM file, so you need to rename `round_1_1.paf` to `round_1_1.sam`. This should resolve this issues.

Best regads,
Robert

**Comment by fengyuanli304** [comment]
Thank you for your reply. I will try it.
