### ISSUE TITLE
What does the no-trimming flag do?

### ISSUE THREAD

**Issue by zacksaud** [isovic/racon#168]
Hi,

Firstly, many thanks for this excellent piece of software. My question concerns the no-trimming feature. What exactly does this do? Does it  not trim the end of reads to fit the assembly? Or does it not trim the extreme ends of contigs if there is very low coverage there?

Many thanks in advance

Best

Zack

**Comment by rvaser** [comment]
Hello Zack,
the `--no-trimming` option disables consensus trimming in each window. Racon creates partial order graphs within non-overlapping windows of each contig, and the consensus calling algorithm can have low coverage ends. Therefore we trim away bases from each consensus sequence until the base coverage reaches half the coverage of the corresponding window.

Best regards,
Robert

**Comment by zacksaud** [comment]
Dear Robert,

Many thanks for this information.

Best Zack
