### ISSUE TITLE
Contigs missing in the output

### ISSUE THREAD

**Issue by ctxchris** [isovic/racon#17]
HI,

I noticed that some contigs are missing in the final output. Are contigs with insufficient coverage thrown out?
Could you include those or write them in an extra file?

Thanks
Chris

**Comment by isovic** [comment]
Hi Chris,
We're planning to put in an option to write contigs which weren't corrected (due to lack of mapped reads) to an additional file.
I'll post here as soon as we implement it.

Best regards,
Ivan.

**Comment by isovic** [comment]
Until then you could use grep/or a custom script to find the missing contigs.

I'll get back on this soon.

Ivan

**Comment by rvaser** [comment]
Version 1.0.0 has an option for this (although, it prints the unpolished contigs together with polished ones):

    -u, --include-unpolished
        output unpolished target sequences (each sequence contains a tag in
        its header (C:<float>) which represents the percentage of polished
        windows)
