### ISSUE TITLE
How to create overlaps?

### ISSUE THREAD

**Issue by bioramg** [isovic/racon#170]
Hi,
I would like to use Racon for my ONT contigs. I am having ONT contigs output from Canu and Illumina reads. I extracted potential ONT contigs and would like polish using Illumina reads. But I could not understand what does mean by Overlaps file and how to create it?
Thank you.

**Comment by rvaser** [comment]
Hi,
you need to map all the reads to your contigs. For example with minimap2 run the following:
```bash
minimap -t <threads> -x sr canu_contigs.fasta illumina_reads.fastq > overlaps.paf
```
and afterwards run racon as below:
```bash
racon -t <threads> illumina_reads.fastq overlaps.paf canu_contigs.fasta > polished_canu_contigs.fasta
```

Best regards,
Robert

**Comment by bioramg** [comment]
Dear Roberts,
Thank you so much for your suggestions.

I would like to know is it possible to use Illumina read files as a separate files rather than combined reads?

Best regards,
Raman. G

**Comment by rvaser** [comment]
Unfortunately no, you need to comine the paired end reads. There is a script [here](https://github.com/isovic/racon/blob/master/scripts/racon_preprocess.py) that does that for you.
