### ISSUE TITLE
Incorrect indel calling for haploid

### ISSUE THREAD

**Issue by DewBudd** [isovic/racon#171]
I'm using Racon on haploid ONT data and I've noticed that it introduces indels that are not supported by the sequencing data. There will be 12/60 reads that have a deletion at a location and Racon deletes the base but since this is haploid data I would prefer it not to delete that base. I've tried a variety of gap penalties but I've not seen an improvement. Do you have any suggestions?

**Comment by rvaser** [comment]
Hi Kelly,
not sure what causes the indel introduction, you might want to try option `--no-trimming` which will disable consensus cutting on both window ends. If there are a lot of reads supporting this area, this is the only thing that comes to my mind that could introduce indels.

Best regards,
Robert

**Comment by DewBudd** [comment]
Unfortunately, that did not fix the problem. I'm wondering if it could be a mapping issue. When I view the sam file that I use as input into Racon with IGV, its metric bar at the top will indicate 50% of the reads have a deletion when it is < 25%. Those are the areas where Racon deletes the base.

**Comment by rvaser** [comment]
Which mapper did you use? Can you share a printscreen of IGV pointing at the problematic area?

**Comment by DewBudd** [comment]
I've used both `minimap2 -ax map-ont` and `bwa mem -x ont2d` with default settings. The screenshot below is from minimap2 but it looks almost identical for the bwa mem alignment.
![igv_snapshot](https://user-images.githubusercontent.com/39844017/99562031-dd4a7b80-2984-11eb-9785-180f059b233b.png)

**Comment by DewBudd** [comment]
Apparently IGV was hiding single bp indels and that was the problem. I tried another viewer and the deletion was apparent. Thank you for your help.
