### ISSUE TITLE
Segmentation fault after loading sequence

### ISSUE THREAD

**Issue by cbirbes** [isovic/racon#173]
Hello, I have been using racon for a very long time to polish my genomes, I even did a nextflow pipeline using racon without problems.
Recently I have encountered a problem on a genome that I want to polish with CLR reads (usually I use ONT)

I am having the following problem:
```
racon::Polisher::initialize] loaded target sequences 12.395108 s
/var/spool/slurm/d/job21101485/slurm_script : ligne 7 : 102585 Segmentation fault  racon -t 20 longreads.rename.fq.gz map.polisher.sam offspring_raw.cgt.fa > assembly.racon3.fa
```

My command :
```
minimap2 -a -t 16 -x map-pb offspring_raw.cgt.fa ${reads} > map.polisher.sam

Racon 1.4.10
racon -t 20 longreads.rename.fq.gz map.polisher.sam offspring_raw.cgt.fa > assembly.racon3.fa
```

Ty for your help

**Comment by rvaser** [comment]
Hi Clement,
can you try the same command with the newest version (1.4.13)? Also, can you paste the compilation commands you used? Running on cluster might be a problem if you compiled on one node and run on another.

Best regards,
Robert

**Comment by cbirbes** [comment]
I'm not admin on the cluster
I will ask for the version update, but i think Running on this cluster is not a problem, i did more than 100 polishing in the past year and 99% worked (sometimes memory problem, but nothing more)

I come back with more information soon !

**Comment by rvaser** [comment]
Was the executable compiled from source or are you using the conda version?

**Comment by cbirbes** [comment]
From source

**Comment by rvaser** [comment]
If you can recompile, use `-Dspoa_optimize_for_portability=ON` when running cmake. This might solve the problem. If not, try updating the version.

**Comment by cbirbes** [comment]
Ok, I tried several things but finally the error came from me. Small file notation error so I had a fastq file which was in fact a fasta ... so successive> and @, but each time with sequences and not qualities!
Thank you for your help !
