### ISSUE TITLE
Different types of reads data to polish

### ISSUE THREAD

**Issue by wjj666** [isovic/racon#175]
I want to use Illumina reads, Matepair reads, ONT reads and PacBio reads to polish assembly with Racon. Should I run racon four times with Illumina reads, Matepair reads, ONT reads and PacBio reads respectively?  or use some specific parameter?

**Comment by rvaser** [comment]
Hi Lulu,
you can combine ONT and Pacbio reads together in one file, and run two iterations of Racon. Afterwards, combine Illumina and Matepair reads together with https://github.com/isovic/racon/blob/master/scripts/racon_preprocess.py and run one iteration of Racon.

Best regards,
Robert

**Comment by wjj666** [comment]
How about the sam files? 
At the first iterations of Racon, the sam file is the alignments between ONT reads and contigs? 
At the second iterations of Racon, the sam file is the alignment between Pacbio reads and contigs?

**Comment by rvaser** [comment]
If you combine the reads in one file, the SAM files will contain both ONT and PB reads vs contigs in both iterations.
