### ISSUE TITLE
racon_wrapper and wrong paths to racon and rampler

### ISSUE THREAD

**Issue by hmontenegro** [isovic/racon#178]
When I compile and install Racon with:

```
curl -LOJR https://github.com/isovic/racon/releases/download/1.4.3/racon-v1.4.3.tar.gz
tar -x -z -f racon-v1.4.3.tar.gz
mkdir racon-v1.4.3/build
cd racon-v1.4.3/build/
cmake -Dracon_build_wrapper=ON -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$HOME/bin/Racon ..
make
make install
cp bin/racon_wrapper ~/bin/Racon/bin/
```
racon_wrapper has hard-coded the source path for racon and rampler, not the destination path:

```
class RaconWrapper:

    __racon = '/home/monte/src/Racon/racon-v1.4.3/build/bin/racon'
    __rampler = '/home/monte/src/Racon/racon-v1.4.3/build/vendor/rampler/bin/rampler'
```
Instead of `/home/monte/bin/Racon/bin`, where the binaries of racon and rampler are installed.

**Comment by rvaser** [comment]
Hello,
the make install command does not include racon_wrapper. According to your snippet you manually copied the wrapper to bin/. You might as well change the racon/rampler paths manually.

Best regards,
Robert
