### ISSUE TITLE
[RaconWrapper::run] error: unable to find split target sequences!

### ISSUE THREAD

**Issue by carolhsb** [isovic/racon#182]
Hi, 

I'm running racon_wrapper to polish an assembly (that I had previously corrected with PacBio reads) with Illumina reads.

This is the command I'm using:

python3 /home/carol/racon/build/bin/racon_wrapper -t 30 --split 28048207 /home/carol/short_reads_mma/concat.clean.fq.gz ./dbg.illumina.sam ./dbg.corrected.pb.fasta > dbg.corrected.illumina.fasta 

I keep getting this error:
[RaconWrapper::run] total number of splits: 0
[RaconWrapper::run] error: unable to find split target sequences!

In the split flag, I used the largest contig value.

How can I work it out?

Thanks in advance,

Carol

**Comment by rvaser** [comment]
Hi Carol,
which Racon version are you using? How big is the assembly? The command you used seems fine to me at first glance.

Best regards,
Robert

**Comment by carolhsb** [comment]
Hi Robert,

Thank you for your answer!

I'm using version 1.4.21. The assembly has 1.37 GB.

Cheers,

Carol

**Comment by rvaser** [comment]
Please run the below command from the racon root folder and check if anything is created: 
`build/vendor/rampler/bin/rampler split dbg.corrected.pb.fasta 28048207`

**Comment by rvaser** [comment]
Scratch that, I found the bug.

**Comment by carolhsb** [comment]
Hi Robert,

I've tried and it works...it splits the contigs

**Comment by rvaser** [comment]
You can pull the new commit and recompile. It should work now.

**Comment by carolhsb** [comment]
> You can pull the new commit and recompile. It should work now.

Ok. I will do it.

Thank you so much!!

**Comment by rvaser** [comment]
Don't forget to run `git submodule --update --recursive`.

**Comment by carolhsb** [comment]
It's working now! :)
thank you
