### ISSUE TITLE
racon generates empty fasta output

### ISSUE THREAD

**Issue by carolhsb** [isovic/racon#183]
Hi Robert,

Me again.
Racon runs without errors, but it outputs an empty fasta file. I've tried twice and got the same result.
I'm using racon version 1.4.21.

This is the command I'm using:
python3 /home/carol/racon/build/bin/racon_wrapper -t 30 --split 28048207 /home/carol/short_reads_mma/concat.clean.fastq.gz ./dbgAGAIN2.illumina.sam ./dbgAGAIN2.corrected.fasta > dbgAGAIN2.corrected2.fasta

This is the log:
RaconWrapper::run] preparing data with rampler
[RaconWrapper::run] total number of splits: 42
[RaconWrapper::run] processing data with racon
[racon::Polisher::initialize] loaded target sequences 0.289602 s

Thank you,

Carol

**Comment by rvaser** [comment]
Hi Carol,
is that the whole log?

Best regards,
Robert

**Comment by carolhsb** [comment]
> Hi Carol,
> is that the whole log?
> 
> Best regards,
> Robert

Yes...

**Comment by rvaser** [comment]
Might be that it got killed due to insufficient memory. How much RAM do you have and how big is the concat.clean.fastq.gz file?

**Comment by carolhsb** [comment]
> Might be that it got killed due to insufficient memory. How much RAM do you have and how big is the concat.clean.fastq.gz file?

The concat.clean.fastq.gz file has 57GB and I got 250 GB of RAM

**Comment by rvaser** [comment]
Can you please run `gzip -dc concat.clean.fastq.gz | wc -c`? It will print the uncompressed file size.

**Comment by carolhsb** [comment]
I did it and the file has 173943628896

**Comment by rvaser** [comment]
I think that this Illumina run will not fit into your RAM (or it will hit swap memory and take a long time finish), either with or without the wrapper.

**Comment by carolhsb** [comment]
> I think that this Illumina run will not fit into your RAM (or it will hit swap memory and take a long time finish), either with or without the wrapper.

That's odd, because I've polished an assembly with PacBio subreads (166 G) in the same sever without any problems

**Comment by rvaser** [comment]
For short reads, the overhead of storing them in memory (~1.5x FASTQ) is greater than for long reads (~1x FASTQ).

**Comment by carolhsb** [comment]
> For short reads, the overhead of storing them in memory (~1.5x FASTQ) is greater than for long reads (~1x FASTQ).

Oh, I understand it.
Thank you for your time 

Best regards

**Comment by rvaser** [comment]
Hopefully, we will update Racon in the near future to use less memory. :)
