### ISSUE TITLE
Racon cmake build error

### ISSUE THREAD

**Issue by MrDotOne** [isovic/racon#186]
I am trying to build racon on our HPC and get the following error:

[root@cc-dclrilog51 build]# cmake -DCMAKE_INSTALL_PREFIX=/cm/shared/apps/racon/1.4.3 -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
[CMakeOutput.log](https://github.com/isovic/racon/files/6175928/CMakeOutput.log)

-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:51 (add_subdirectory):
  The source directory

    /root/temp/racon-master/vendor/bioparser

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:54 (add_subdirectory):
  The source directory

    /root/temp/racon-master/vendor/spoa

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:57 (add_subdirectory):
  The source directory

    /root/temp/racon-master/vendor/thread_pool

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:60 (add_subdirectory):
  The source directory

    /root/temp/racon-master/vendor/edlib

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/root/temp/racon-master/build/CMakeFiles/CMakeOutput.log".

I have the following environment modules loaded:

[root@cc-dclrilog51 build]# module list
Currently Loaded Modulefiles:
  1) shared              3) cmsh                5) cluster-tools/7.0   7) cmake/3.9.1         9) python/3.6.2
  2) cmgui/7.0           4) cmd                 6) slurm/14.03.0       8) gcc/8.3.0          10) minimap2/2.17

Any thoughts?

**Comment by rvaser** [comment]
Hello,
either run `git submodule update --init --recursive` or download the complete source code from https://github.com/lbcb-sci/racon/releases/download/1.4.20/racon-v1.4.20.tar.gz

Best regards,
Robert

**Comment by MrDotOne** [comment]
Thank you, i will give that a try. OK, that got me through the config phase but it fails to compile with the following:

Scanning dependencies of target spoa
[ 59%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
In file included from /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:14,
                 from /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:12:
/root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before ‘Alignment’
/root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: ‘Alignment’ has not been declared
/root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected ‘;’ before ‘=’ token
/root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before ‘=’ token
/root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:50: error: ‘Alignment’ does not name a type
/root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:53: error: ‘Alignment’ does not name a type
In file included from /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:12:
/root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:30: error: expected ‘;’ before ‘override’
/root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:32: error: ‘Alignment’ does not name a type
/root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:47: error: ‘Alignment’ does not name a type
/root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:50: error: ‘Alignment’ does not name a type
/root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:53: error: ‘Alignment’ does not name a type
/root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:60: error: expected ‘;’ before ‘noexcept’
In file included from /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:13:
/root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:30: error: expected ‘;’ before ‘override’
/root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:32: error: ‘Alignment’ does not name a type
/root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:48: error: expected constructor, destructor, or type conversion before ‘linear’
/root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:52: error: expected constructor, destructor, or type conversion before ‘affine’
/root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:56: error: expected constructor, destructor, or type conversion before ‘convex’
/root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:65: error: expected initializer before ‘noexcept’
/root/temp/racon/vendor/spoa/src/alignment_engine.cpp: In function ‘std::unique_ptr<spoa::AlignmentEngine, std::default_delete<spoa::AlignmentEngine> > spoa::createAlignmentEngine(spoa::AlignmentType, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)’:
/root/temp/racon/vendor/spoa/src/alignment_engine.cpp:64: error: ‘nullptr’ was not declared in this scope
/root/temp/racon/vendor/spoa/src/alignment_engine.cpp: At global scope:
/root/temp/racon/vendor/spoa/src/alignment_engine.cpp:77: error: ‘Alignment’ does not name a type
make[2]: *** [vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[1]: *** [vendor/spoa/CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

**Comment by zzzqiii** [comment]
> Thank you, i will give that a try. OK, that got me through the config phase but it fails to compile with the following:
> 
> Scanning dependencies of target spoa
> [ 59%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
> In file included from /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:14,
> from /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:12:
> /root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected nested-name-specifier before ‘Alignment’
> /root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: ‘Alignment’ has not been declared
> /root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected ‘;’ before ‘=’ token
> /root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:30: error: expected unqualified-id before ‘=’ token
> /root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:50: error: ‘Alignment’ does not name a type
> /root/temp/racon/vendor/spoa/include/spoa/alignment_engine.hpp:53: error: ‘Alignment’ does not name a type
> In file included from /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:12:
> /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:30: error: expected ‘;’ before ‘override’
> /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:32: error: ‘Alignment’ does not name a type
> /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:47: error: ‘Alignment’ does not name a type
> /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:50: error: ‘Alignment’ does not name a type
> /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:53: error: ‘Alignment’ does not name a type
> /root/temp/racon/vendor/spoa/src/sisd_alignment_engine.hpp:60: error: expected ‘;’ before ‘noexcept’
> In file included from /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:13:
> /root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:30: error: expected ‘;’ before ‘override’
> /root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:32: error: ‘Alignment’ does not name a type
> /root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:48: error: expected constructor, destructor, or type conversion before ‘linear’
> /root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:52: error: expected constructor, destructor, or type conversion before ‘affine’
> /root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:56: error: expected constructor, destructor, or type conversion before ‘convex’
> /root/temp/racon/vendor/spoa/src/simd_alignment_engine.hpp:65: error: expected initializer before ‘noexcept’
> /root/temp/racon/vendor/spoa/src/alignment_engine.cpp: In function ‘std::unique_ptr<spoa::AlignmentEngine, std::default_deletespoa::AlignmentEngine > spoa::createAlignmentEngine(spoa::AlignmentType, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)’:
> /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:64: error: ‘nullptr’ was not declared in this scope
> /root/temp/racon/vendor/spoa/src/alignment_engine.cpp: At global scope:
> /root/temp/racon/vendor/spoa/src/alignment_engine.cpp:77: error: ‘Alignment’ does not name a type
> make[2]: *** [vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
> make[1]: *** [vendor/spoa/CMakeFiles/spoa.dir/all] Error 2
> make: *** [all] Error 2

Hi, I got the the same error when I tried to make. Have you solved it?

**Comment by rvaser** [comment]
@MrDotOne, I am sorry but I did not get a notification for your edited question. The error you have means that your compiler does not meet the minimum required version.

@zzzqiii, the same error. I will answer your question in #190.
