### ISSUE TITLE
Unequal lengths in target and overlap file for target

### ISSUE THREAD

**Issue by jules-o** [isovic/racon#188]
Hi,

I'm sure there's something really obvious here that I'm missing. I ran racon (in Galaxy) to polish a sequence assembled by Flye from Oxford Nanopore data, with the raw nanopore reads as the sequences and a paf overlaps file generated by minimap2 from the raw reads. That worked well, but now I'm trying to do another round of polishing, using the same reads, same overlaps file and all the same settings, except with the output from the first round as the target sequence - and I keep getting "error: unequal lengths in target and overlap file for target contig_1!"

I've tried normalizing the fasta from the first round, also copying the sequence and pasting it straight into a new file in case white spaces or something had somehow got inserted, but it's the same error each time.

What am I doing wrong?

**Comment by rvaser** [comment]
Hello,
you need to create a new overlap file for each iteration by mapping reads to the output of the previous iteration.

Best regards,
Robert

**Comment by jules-o** [comment]
Oh I see - thank you. And sorry for the stupid question. I had misunderstood how the overlaps file is supposed to be created. Probably surprising that it worked at all the first time, since I'd used all-to-all mapping with only the reads, rather than mapping the reads to the target sequence. That explains why it's more accurate now!
Thank you for your help,
Julia
