### ISSUE TITLE
Github Releases?

### ISSUE THREAD

**Issue by nileshpatra** [isovic/racon#195]
Hi,

Looking at [CmakeLists.txt](https://github.com/isovic/racon/blob/master/CMakeLists.txt#L3), it looks like that the current racon release is 1.4.17?

However the last release that was git-tagged and/or released is 1.4.3, which was released more than 2 years ago!

Could you please tag the versions properly? Atleast the latest version?

This is pretty important to all the linux distributions that ship your package (Bio Linux, Ubuntu, Linux Mint et. al.)

**Comment by nileshpatra** [comment]
Also, apologies for asking this but what is the difference between this repository and this one?: https://github.com/lbcb-sci/racon

The upstream author (rvaser) looks common

**Comment by rvaser** [comment]
Hello,
the lbcb-sci/racon is the new official repository which gets updates, and there are newer releases present (bioconda builds from there as well). Ivan sometimes updates this repository but without any releases.

Best regards,
Robert
