### ISSUE TITLE
empty output file!

### ISSUE THREAD

**Issue by marce-sarrias** [isovic/racon#198]
Hello,

I'm running racon but for some reason I get an empty output file. 

This is my code:

#SBATCH -m 100G
#SBATCH -c 100

racon -m 8 -x -6 -g -8 -w 500 -t 32 ./all.trimmed.fastq.gz ./mapped_reads.paf ./assembly.fasta > ./assembly.racon.fasta

size of my input files:
17G all.trimmed.fastq.gz
637M assembly.fasta
246M mapped_reads.paf

and this is what I get in the standard error file: 
[racon::Polisher::initialize] loaded target sequences 2.601033 s
[racon::Polisher::initialize] loaded sequences 293.831238 s
[racon::Polisher::initialize] loaded overlaps 3.346442 s
[racon::Polisher::initialize] aligning overlaps [====================] 1257.327412 s
[racon::Polisher::initialize] transformed data into windows 37.817850 s

Any idea of what the problem is? 

Thank you!!

Marcela

**Comment by rvaser** [comment]
Hi Marcela,
is there any error code reported by slurm? Is it still running? Do you have a time constraint on the server?

Best regards,
Robert

**Comment by marce-sarrias** [comment]
Hi Robert, 

Sorry for my late response. I do not get any error, I only get something like this (see below):

[racon::Polisher::initialize] loaded target sequences 2.601033 s
[racon::Polisher::initialize] loaded sequences 293.831238 s
[racon::Polisher::initialize] loaded overlaps 3.346442 s
[racon::Polisher::initialize] aligning overlaps [====================] 1257.327412 s
[racon::Polisher::initialize] transformed data into windows 37.817850 s

I can use up to 500 cores and 2000G total memory for 14 days. In this case racon run for about 20 min. I tried running it using the test data and I have the same problem (no errors and empty output file). 

Marcela

**Comment by rvaser** [comment]
Weird. Which version are you using? Did you compile from source or are you using the conda executable?

**Comment by marce-sarrias** [comment]
Hi, 

I just did this: 

git clone --recursive https://github.com/lbcb-sci/racon.git racon
cd racon
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make

**Comment by marce-sarrias** [comment]
I also tried using a sam file instead of paf and still have the same issue.

**Comment by rvaser** [comment]
Try running `cmake -Dspoa_optimize_for_portability=ON -DCMAKE_BUILD_TYPE=Release ..` and `make` (from racon/build).

**Comment by marce-sarrias** [comment]
Hi Robert! 

It worked! Thanks!!

Marcela
