### ISSUE TITLE
Stuck at first consensus window

### ISSUE THREAD

**Issue by jaesvi** [isovic/racon#2]
Hi. 
I am running Racon with a ~45 Mb Miniasm assembly purely from ONT reads. I aligned the reads (2D Pass only) with GraphMap. I first tried Racon with default parameters and I got the same input reference as output, without changes. Then I removed the quality filtering to check if it was the problem and it seems it was, because now it finds the alignments. However, it has been stuck on the first processing window for two days now, and looking at your poster from London Calling and by common sense, it should be way past there. But the process seems to be still running, as it shows so when doing 'top'.
This is the line where its stuck:
`[13:58:42 CreateConsensus] (thread_id = 0) Processing window: 0 bp to 499 bp (0.00%), coverage: 8x`

And this is the command:
`racon -t 8 --bq -1  miniasm.fasta 2d.miniasm.sam miniasm.racon.fasta`

**Comment by isovic** [comment]
Hi,
can you try a git pull and letting me know if it works now?
Thank you for the report!

Best regards,
Ivan.

**Comment by jaesvi** [comment]
It does not look like it, still gets stuck. To add a bit of info to the issue, looks like sometimes it is able to get through the first window to the second or even the third. This is always removing the quality filter. When I look at my sam file, it looks like it does have the quality values:
`awk '{print $5}' 2d.miniasm.sam | sort | uniq -c`
    308
     43 1
    101 2
   5221 255
   1056 3
  71378 40
      1 -t

Always assuming that field 5 is the one that you refer as quality values. This sam was generated with GraphMap so it should work fine. So I think there are two problems for me right now. First the quality filter does not work when it should and second when the quality filter is removed Racon blocks at the first window(s).
Cheers,
Jose

**Comment by isovic** [comment]
Hi Jose,

I tried to reproduce your issue, but I can't seem to do so...could you by any chance share a minimal example which doesn't work? I'd like to resolve it and make Racon more usable.
There is one more thing I can suggest which might not have been done automatically by the Makefile, could you try this:  
```  
cd codebase/seqlib  
git checkout master  
git pull  
```  
And then go back into the root folder of racon and do ```make clean``` and ```make```, and re-running your test?

Regarding the info you sent - actually the quality values we're referring to are the base qualities (field #11 in the SAM format), while field #5 is the mapping quality.
The quality filter ("--bq" option) refers to filtering chunks of the read sequences which have bases of poor quality (< 10 Phred score by default). This increases the final consensus result as the poor quality bases do not influence the statistics.

Best regards,
Ivan.

**Comment by jaesvi** [comment]
Dear Ivan,

I was suspecting that I was doing something wrong with the quality values and it was indeed the case. I thought that you referred to _mapping_ quality values The _base_ quality values are not in my SAM file since I was mapping a fasta file with GraphMap. This morning I tried with a Fastq file and now Racon seems to be working like a charm. 
I think you should make this more clear in the README, or create an error message when the base quality values cannot be found. Sorry for all the inconvenience created and thanks for all the help.
Cheers, 
Jose

**Comment by isovic** [comment]
Dear Jose,

I'm happy that Racon finally worked for you, thank you for the feedback!
Also, your suggestion is quite good, I'll make it clearer and put a sanity check in the code as well to not allow usage of SAM files which do not have BQs.

Thanks again!
Best regards,
Ivan.
