### ISSUE TITLE
Does polishing with Racon requieres generation of new .sam files?

### ISSUE THREAD

**Issue by VadimRakitin** [isovic/racon#216]
I want to apply multiple polishing steps with racon. Should I create between every polishing step new .sam file with racon_polish.fa file? or Can I use the same .sam file everytime, and just change with every polishing the backbone (racon_polish_1.fa, than racon_polish_2.fa etc.)

**Comment by rvaser** [comment]
Hi Vadim,
you need to recreate the .sam/.paf file in each iteration as the backbone sequences are changing.

Best regards,
Robert
