### ISSUE TITLE
Issue with some files resulting in "overlap is not transmuted"

### ISSUE THREAD

**Issue by PSSchacksen** [isovic/racon#223]
I have made a NP run with 80 different barcodes, seperated by porechop, trimmed etc.
Then run through minimap followed my racon (didnt know how to make the loop with racon based on matching file names so BC01 - BC80 are as the example).

For some of the polishing files with racon files are working just fine, while for others the "overlap is not transmuted" error occurs.

Since my "OTUtable/6_zotus_cat/6_zotus_comb.fa" file is a combined file of all my barcodes, I find it weird that multiple, seemingly random, files results in this error. If needed i can share more of my script. (the zotus file is made using vsearch --cluster_unoise followed by cat)

```
input="OTUtable/5_zotus/"
output="OTUtable/7_minimap"

files=$(find "$input" -type f -iname '*.fa')
for file in $files
do
 minimap2 \
  -ax map-ont \
  -t 22 \
  $file \
  OTUtable/6_zotus_cat/6_zotus_comb.fa \
  > "${output}/$(basename "${file%.*}")_aln.sam"
done

racon OTUtable/6_zotus_cat/6_zotus_comb.fa OTUtable/7_minimap/BC01_filtered_cut_zotus_aln.sam OTUtable/5_zotus/BC01_filtered_cut_zotus.fa -t 22 > OTUtable/8_racon/BC01_filtered_cut_zotus_pol.fa
```

racon version 1.3.3, the same happens if the "--include-unpolished" option is used

**Comment by rvaser** [comment]
Hello,
can you please try with the latest version (1.5.0)?

Best regards,
Robert

**Comment by PSSchacksen** [comment]
Im currently waiting for my server admin to update the version, but I will redo the program and come back with the results.

**Comment by PSSchacksen** [comment]
After rerunning with racon 1.5.0 the issue has been fixed, thanks 👍
