### ISSUE TITLE
installation on CentOS 7: 'Could NOT find ZLIB: Found unsuitable version "1.2.7", but required is at least "1.2.8"'

### ISSUE THREAD

**Issue by hanrong-chen** [isovic/racon#235]
Hello!
I'm trying to install racon on CentOS 7. When I run `cmake -DCMAKE_BUILD_TYPE=Release ..` I get the following error:
> CMake Error at /home/centos/cmake-3.26.0-rc6-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find ZLIB: Found unsuitable version "1.2.7", but required is at
>   least "1.2.8" (found /usr/lib64/libz.so, )
> Call Stack (most recent call first):
>   /home/centos/cmake-3.26.0-rc6-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
>   /home/centos/cmake-3.26.0-rc6-linux-x86_64/share/cmake-3.26/Modules/FindZLIB.cmake:200 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   build/_deps/bioparser-src/CMakeLists.txt:22 (find_package)

I installed zlib 1.2.13 following [these](https://unix.stackexchange.com/a/476452) instructions but the error persists. I suspect I need to tell CMake where to find the library at compile time, but am unfamiliar how to do so. Would you know a solution for this? Thank you!

**Comment by rvaser** [comment]
Hello,
maybe `-DZLIB_LIBRARY=<path to library> -DZLIB_INCLUDE_DIR=<path to include>` while running cmake.

You can also use racon through bioconda: https://anaconda.org/bioconda/racon.

Best regards,
Robert
