### ISSUE TITLE
Empty Output (non-memory-related issue)

### ISSUE THREAD

**Issue by lidi4** [isovic/racon#236]
Hello,

I've been trying to run Racon for the first time on one ONT dataset ([here](https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR12390956&display=metadata))

Each time I try to run it, with or without the specified options, it runs very quickly with no errors and spits out an empty file. What is happening here? Any help would be so appreciated!!

My command: 
`racon -m 8 -x -6 -g -8 SRR12390956.fastq aln-se.sam assembly.fasta > polished1_assembly.fasta`

Log:
[racon::Polisher::initialize] loaded target sequences 0.001896 s
[racon::Polisher::initialize] loaded sequences 0.364408 s
[racon::Polisher::initialize] loaded overlaps 0.328071 s
[racon::Polisher::initialize] aligning overlaps [====================] 0.563149 s
[racon::Polisher::initialize] transformed data into windows 0.046840 s
[racon::Polisher::polish] generating consensus [====================] 0.002845 s
[racon::Polisher::] total = 1.317226 s

Racon is being operated in its own conda env.

Data on the read input file:
number of sequences:  7911
number of base pairs: 54 Mbp
Read file size: 2.2G

Assembly file generate with Flye (metaFlye)
SAM file generated with BWA

according to metaQUAST assembly QC, the assembly file has 25 contigs ( if that's helpful, idk)
all three input files are valid and full, no corruption.

Not sure how/why, but when I check racon version it says 1.5.0 despite that appearing to be too high of a version? I can't explain that

**Comment by rvaser** [comment]
Hello,
The fastq file you are using has all qualities set to `$` which is QV3, while racon has:
```
    -q, --quality-threshold <float>
        default: 10.0
        threshold for average base quality of windows used in POA
```
which means all reads are filtered out and no polishing is done.

Regarding v1.5.0, racon development has been transfered to lbcb-sci/racon repository some time ago.

Best regards,
Robert

**Comment by rvaser** [comment]
If this does not resolve your issue, please reopen.

**Comment by lidi4** [comment]
Thank you so much!! I will let you know if anything else pops up asap.
