### ISSUE TITLE
racon: invalid option -- 'L'

### ISSUE THREAD

**Issue by yeeus** [isovic/racon#238]
Hello, I am following the polishing method of Mc Cartney et al., 2022, whose doi is https://doi.org/10.1038/s41592-022-01440-3, where Racon's liftover branches were used(https://github.com/isovic/racon/tree/liftover). Here is the command:
`${RACON} -t ${threads} ${in_dataset} ${out_falconc_sam} ${in_draft} -L ${out_racon_fasta} -S > ${out_racon_fasta}`

But when I tried this script, I got an error `racon: invalid option -- 'L'`. It seems that this version the paper used was discarded, so I have the question that whether you would re-release that or never? And if you won't, can you tell me how to get the vcf file the script need?

Best wishes!

**Comment by btrainee** [comment]
I encountered the same situation，have you solved it ?

**Comment by yeeus** [comment]
> I encountered the same situation，have you solved it ?

I didn't solve it and tried another method.

**Comment by laowang1992** [comment]
As you are following the polishing method of Mc Cartney et al., 2022, `falconc` may be also installed by `conda install pbipa`. Then, a `racon` will also be installed by the command `conda install pbipa`.
Try:
```shell
which racon
```
Make sure is that `racon` you need, if not, add it to PATH after `falconc`.

**Comment by jjwujay** [comment]
Ref https://github.com/arangrhie/T2T-Polish/blob/master/automated_polishing/README.md
we can
git clone https://github.com/isovic/racon.git
cd racon
git checkout liftover
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
