### ISSUE TITLE
Make creates lots of prcessors and overloads server, which kills compilation

### ISSUE THREAD

**Issue by mw55309** [isovic/racon#30]
I am trying to compile racon.

make modules finishes fine.

I then tried "make tools" and got lots of "out of memory errors" and:

g++: internal compiler error: Killed (program cc1plus)

So then I tried:

make -j 1 tools

This should limit the jobs to 1; however, look at the attached screenshot - 
![raconwut](https://cloud.githubusercontent.com/assets/1777488/26541613/44fa41ae-444e-11e7-8118-5ed073996b6a.png)

What the....?

Compilation is being killed by the OS

How do I fix this?

Cheers
Mick

**Comment by mw55309** [comment]
FYI I substituted all instances of "-j" with "-j 1" in the Makefile and this solved the issue

**Comment by isovic** [comment]
Whoops :-)
Thanks for reporting this.
I pushed a fix removing all `-j` entries from the Makefile.

Best regards,
Ivan.
