### ISSUE TITLE
Racon seems to get stacked during consensus building

### ISSUE THREAD

**Issue by fg6** [isovic/racon#32]
Hi,
I am trying to use racon to polish a fish miniasm assembly (~600 Mbases) from pacbio data.
I have tried my racon script on an ecoli assembly  and it works fine, but on this fish it seems racon
get stucked at some point during the consensus generation. 
To simplify the problem as much as possible I selected a unique contig (~5 Mbases) and aligned
about 50K reads against only this contig with bwa mem, then filtered out all supplementary, secondary and duplication alignments and tried to run racon on this subset, but it still seems to get stucked around the same point.

I am running racon v0.5.0 like this:
`$raconhome/bin/racon -v 7 -M 5 -X -4 -G -8 -E -6 --bq 0 --sam -t 15 selected.fastq bwa.sorted.sam results/consensus-${dataset}-${suffix}-$previter.fasta   results/consensus-${dataset}-${suffix}-$curriter.fasta`

An example of output (-v 7) below, everytime it seems to get stucked in a slightly different position, but always around 0.05% of the consensus. The job seems to keep working, but even if I leave it running it just never ends. I have tried many subsettings but it just get stucked and never ends. it keeps using 15 cpus, but is not clear what it's doing, and no progress seems to be made...
Can you please advise what could be wrong? Maybe the pacbio accuracy could be too low?

Thank you very much!
Francesca 

> [14:44:41 main] Using SAM for input alignments. (bwa.sorted.sam)
> [14:44:41 main] Parsing the SAM file.
> [14:44:50 ConsensusFromAln] Running consensus - directly from alignments.
> [14:44:50 ConsensusFromAln] Separating alignments to individual contigs.
> [14:44:50 ConsensusFromAln] In total, there are 1 contigs for consensus, each containing:
> [14:44:50 ConsensusFromAln] 	[0] utg000004l 50000 alignments, contig len: 5133663
> [14:44:50 ConsensusFromAln] Starting consensus for contig 1 / 1 (100.00%): utg000004l
> [14:44:50 src/consensus/consensus_sam.cc CreateConsensusAln LN:277] current_contig->get_sequence_length() = 5133663, parameters.window_len = 500, num_windows = 10268
> [14:44:50 src/consensus/consensus_sam.cc CreateConsensusAln LN:291] CPU time for building the IntervalTree: 0.130000 sec.
> [14:44:50 CreateConsensusAln] (thread_id = 0) Processing window: 2500 bp to 2999 bp (0.05%)[14:44:50 src/consensus/consensus_sam.cc CreateConsensusAln LN:316] , clk_total_extract = 0.000000, clk_total_spoa = 0.000000, coverage: 264x

**Comment by rvaser** [comment]
Hello Francesca,
it is hard to tell what went wrong from the above snip, I guess an infinite loop somewhere. Could you share the data that causes this problem so we can debug the problem locally? The smaller the data subset the better.

Best regards,
Robert

**Comment by fg6** [comment]
Hi Robert, 
thanks for your quick reply and thanks for the help! 
I have prepared a small folder with:
- fasta assembly to polish: split_000000.fasta
- pacbio reads: selected.fastq
- sam file of the pacbio reads aligned against the fasta assembly: bwa.sorted.sam
- the script I used to generate the sam file: bwa.sh
- the script I use to run racon: racon.sh
The file is here:
[https://drive.google.com/open?id=0B_5keXxfARKheVhKUHdsdmNEcDg]

Let me know if you need more information!
Thank you!
Francesca

**Comment by rvaser** [comment]
Dear Francesca,
the problem is in your quality values, all of them are (I assume manually) set to '!' which equals to phred score of zero. Phred scores are part of edge weights in the partial order graph and if all of them equal to zero, the current implementation is unable to locate the maximum path (consensus) in the graph, as all paths equal to zero. I am not sure how to circumvent this in consensus generation, but you can easily prevent this problem by replacing all qualities '!' with any ASCII character greater than '!', so that the edge weights are equal or greater to 1. Be sure to rerun BWA as reads and their qualities are read from the .sam file, if one is provided to racon.

Best regards,
Robert

**Comment by fg6** [comment]
Dear Robert,
thanks for your fast fix! Yes the values are all '!', 
I thought asking for '--bq -1' would take care of that?

Anyway, now it's working fine!
Thanks a lot!
Francesca

**Comment by rvaser** [comment]
Dear Francesca,
the option '--bq -1' only disables quality filtering, i.e. parts of reads with avg quality lower than the set parameter (default 10) are dropped. Qualities are also used in consensus generation, as they provide weights for each base in majority vote. We are planning to enable FASTA sequences as input, as many users have requested this feature.

Best regards,
Robert

**Comment by fg6** [comment]
oh I see, thanks for the explanation!

Best,
Francesca
