### ISSUE TITLE
wrong default listed in help

### ISSUE THREAD

**Issue by webbchen** [isovic/racon#33]
Hello,

Minor thing in the help:
The line:
"
        --mhap           -    Overlaps are in PAF format instead of MHAP. [false]
"
should be
"
        --mhap           -    Overlaps are in MHAP format instead of PAF. [false]
"
given that it throws the following error when --mhap flag is _not_ set and an *.mhap file is provided as input: 
"
[Mon, 10 Jul 17 16:10:23 +0000 ERROR] #5: Unexpected value found! Overlaps are not formatted in the PAF format. Exiting. In function: 'ParsePAF'.
"

**Comment by rvaser** [comment]
Hello,
thank you for the note, we will update it in the next release which should be soon.

Best regards,
Robert

**Comment by rvaser** [comment]
Updated in Racon 1.0.0.
