### ISSUE TITLE
racon within qsub

### ISSUE THREAD

**Issue by NicolaDM** [isovic/racon#34]
Hi all,

I am trying to use racon within a qsub script, but I find that while running racon directly from the terminal gives me readable output, running racon from a qsub script always gives me empty output.
For example the command 
racon 2>&1 | wc -c
Gives me completely different results when run within the terminal (result: 2835) than when run within a qsub script (result: 0).
Any ideas/help?

Best wishes,
Nicola

**Comment by rvaser** [comment]
Hello Nicola,
I have never used qsub so I am not able to help you instantly. If you try to submit any other program with qsub to your cluster, does it work the same as running it directly from terminal?

Best regards,
Robert

**Comment by NicolaDM** [comment]
Thanks Robert, fortunately we (kind of) solved the issue. The problem was that some of the nodes of the cluster do not support AVX, and racon probably requires AVX to run.

Best wishes,
Nicola

**Comment by rvaser** [comment]
If available, Racon uses SSE4.1 instructions. If you want to run it on cluster on all cores where some of them do not support SSE4.1+, compile it without SIMD instructions (normal alignment is implemented as well, although slower). I am glad you were able to solve the issue.

Best regards,
Robert
