### ISSUE TITLE
Number of working threads

### ISSUE THREAD

**Issue by alducluzeau** [isovic/racon#35]
Hi there !

I just wanted to confirm with you that as far as to now, Racon runs only with one thread.
Thus, it is unfit to be used on an HPC for a genome wide job.

Thank you,

Anne-Lise

**Comment by rvaser** [comment]
Hello Anne-Lise,
could you please elaborate on the 1 thread thingy? I am asking because you can specify number of threads with the parameter '-t <int>'.  Does HPC stand for high performance cluster? If so, Racon does not yet support execution on a cluster, but you can try and run Racon on different sets of contigs simultaneously on several cpus of your cluster.

Best regards,
Robert

**Comment by alducluzeau** [comment]
Hello Robert,

Yes, I am trying to run Racon on a high performance cluster and I am new to all the terminology you mentioned but I did a little research this morning. 
My script was flawed as I set up a variable to use 144 cores on 6 nodes while I didn't invoke -t in my command line. Thus, when I checked out the log, I realized that I was using just one node and the working thread was the same for each processed read (thread_ID=0).

Now, if in my script, I do something like ( I skip lines to focus on the -t option):
NUMCORE=144
/bin/racon -t $NUMCORE --erc blah.fq blah.paf blah.fq blah.fa
It will not induce 144 threads to work ?

I think it was a gross mistake of mine to space out on -t. However, I think it is a point that maybe would need to be mentioned on the code page of this repository. As a rookie, I wasn't really looking for it but I know that if I came upon something about it, I would have definitely not spaced out on it in my command line. Then it seems not possible for me to invoke in bash --options or -h. I finally realized my mistake when I looked at the exemple3-erc.sh where I saw for the first time -t. I think that proficient bioinformaticians wouldn't have done this mistake but for newbees like me, obvious mentions of simple things are still useful. :-)

Thanks again for taking the time to help me.

AL

**Comment by rvaser** [comment]
Hello Anne-Lise,
as I mentioned before, Racon won't use all cores on a cluster automatically. I would advise you to run Racon with '-t 24' (I assume that 1 node has 24 cores). If you feel confortable with a bit file management you can run Racon on each core at the same time manually. With error correction mode, split your reads into 6 files, map the whole read set on each of the 6 disjoint subsets and run Racon on each of 6 nodes with '-t 24'. This way you are effectively running on 144 cores.

Most bioinformatics tools have a detailed list of parameters when you run them without any parameters or with '-h' (or '--help').

Best regards,
Robert

**Comment by alducluzeau** [comment]
Thank you Robert, this helps a lot !

Cheers,

AL
