### ISSUE TITLE
Output file blank/script ends abruptly

### ISSUE THREAD

**Issue by timacwalker** [isovic/racon#36]
Hi there,

I'm having a problem with using racon. The racon script appears to end abruptly during consensus building and the output file is blank. I'm not sure what the problem is as all the intermediate steps seemed to work fine and I can't find any error messages or logs. Does anyone have any ideas?

Thanks,

Tim

-------------------------------------------------

#creation of raw contigs using minimap/miniasm

minimap -Sw5 -L100 -m0 -t8 BC01.fastq BC01.fastq | gzip -1 > BC01_reads.paf.gz

miniasm -f BC01.fastq BC01_reads.paf.gz > BC01_miniasm_assembly.gfa

#mapping of raw contigs and reads

minimap BC01_miniasm_assembly.gfa BC01.fastq > BC01_mappings_1.paf

#consensus building with racon

./racon/bin/racon BC01.fastq BC01_mappings_1.paf BC01_miniasm_assembly.gfa BC01_racon_consensus_1.fasta  

[11:50:52 main] Using PAF for input alignments. (BC01_mappings_1.paf)
[11:50:52 main] Loading reads.
[11:51:03 main] Hashing qnames.
[11:51:04 main] Parsing the overlaps file.
[11:51:04 main] Unique overlaps will be filtered on the fly.
[11:51:04 main] Overlaps will be fully aligned.
[11:51:04 ConsensusFromOverlaps] Running consensus.
[11:51:04 ConsensusFromOverlaps] Separating overlaps to individual contigs.
[11:51:04 ConsensusFromOverlaps] In total, there are 1 contigs for consensus, each containing:
[11:51:04 ConsensusFromOverlaps] 	[0] utg000001l 0 alignments, contig len: 10329378

[11:51:04 ConsensusFromOverlaps] Started processing contig 1 / 1 (100.00%): utg000001l

**Comment by rvaser** [comment]
Hello Tim,
you need to extract contigs from 'BC01_miniasm_assembly.gfa' file with the following command:
`awk '$1 ~/S/ {print ">"$2"\n"$3}' BC01_miniasm_assembly.gfa > BC01_miniasm_assembly.fasta`.
Replace the *.gfa file with the newly generated *.fasta file in all subsequent commands.

Best regards,
Robert

**Comment by timacwalker** [comment]
D'oh!

Thanks very much for the help!

Tim.

Sent from my iPhone

On 4 Oct 2017, at 12:16, Robert Vaser <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Tim,
you need to extract contigs from 'BC01_miniasm_assembly.gfa' file with the following command:
awk '$1 ~/S/ {print ">"$2"\n"$3}' BC01_miniasm_assembly.gfa > BC01_miniasm_assembly.fasta.
Replace the *.gfa file with the newly generated *.fasta file in all subsequent commands.

Best regards,
Robert

**Comment by rvaser** [comment]
Hello Tim,
you need to extract contigs from 'BC01_miniasm_assembly.gfa' in order to map reads to them with minimap: `awk '$1 ~/S/ {print ">"$2"\n"$3}' BC01_miniasm_assembly.gfa > BC01_miniasm_assembly.fasta`
You can replace the *.gfa file with the newly generated *.fasta file in all subsequent commands.

Best regards,
Robert
