### ISSUE TITLE
Memory usage difference between racon with sam or paf files

### ISSUE THREAD

**Issue by damlasenol** [isovic/racon#40]
Hello,
I am running Racon with sam file and paf file as input, respectively. What I observe is that racon with paf input consumes almost 2x memory than racon with sam input. What can be the reason for this?
Thank you!

**Comment by isovic** [comment]
Hi,
Which mapper did you use to generate the sam file? It is possible that the aligner you used generates output which is more specific than Minimap1 mappings without alignment, especially in case of shorter repetitive regions.
How many overlaps do you have reported in your .paf file? And how many alignments in the .sam?

Best regards,
Ivan.

**Comment by damlasenol** [comment]
Hi Ivan,
I used BWA-MEM for the .sam files and Minimap1 for the .paf files. There are 251.911 overlaps in .paf file and 176.425 mappings in the .sam file. Is there any algorithmic difference that can cause this memory usage difference? Or is it just because there are more overlaps than mappings?
Thank you.
Best,
Damla

**Comment by rvaser** [comment]
Hi Damla,
are you using Racon for error correction or the default mode (consensus/polishing)?

Best regards,
Robert

**Comment by damlasenol** [comment]
Hi Robert,

For polishing.

Best,
Damla

**Comment by rvaser** [comment]
How large are your SAM and PAF file, respectively?

**Comment by damlasenol** [comment]
SAM file is 4.2GB and PAF file is 34MB.

**Comment by rvaser** [comment]
How are you measuring the memory consumption? Is it twice as large during the whole runtime or just on some parts?

**Comment by damlasenol** [comment]
I just used it with /usr/bin/time -v, so it is the peak memory usage, not the average.

**Comment by rvaser** [comment]
The number of overlaps might indicate why more memory is used in the PAF case (1.45 times more overlaps than the SAM file).

**Comment by damlasenol** [comment]
But in the algorithm, there is not a significant difference that can affect memory usage, right?
Thank you!

**Comment by rvaser** [comment]
Only the POA graphs might increase in size a little due to more sequences added to them.
