### ISSUE TITLE
/bin/ld: cannot find -lstdc++

### ISSUE THREAD

**Issue by rackingmyhead** [isovic/racon#41]
Keep getting this error when trying to run make on racon. System say's file is installed. I am using Cent 7. Can anybody please shed some insights as to why I am getting this.

**Comment by rvaser** [comment]
Hello,
this might help: http://bytefreaks.net/programming-2/centos-7-c-static-linking-cannot-find-lstdc-lm-and-lc

Best regards,
Robert

**Comment by rackingmyhead** [comment]
Thank you so much Robert. That did the trick.

**Comment by eburgueno** [comment]
I am getting this error as well. I'm not really keen on installing static libraries. Any reason you cannot use dynamic linking here?

**Comment by rvaser** [comment]
We prefer static libraries :)
