### ISSUE TITLE
Racon for consensus then error correcting

### ISSUE THREAD

**Issue by jelber2** [isovic/racon#50]
Hi,
Sorry to bother you again, but I have a question about Racon's suggested use.
First, off I took a mammalian de novo assembly (Illumina short-insert [500bp] and long-insert [5kbp] reads) and filled in gaps with 10x coverage PacBio Sequel reads with PBJelly. Then I mapped the PacBio reads to the PBJelly assembly and created a consensus with Racon (using --bq -1). Now I would like to error correct the Racon assembly with the original Illumina short-insert reads used for the de novo assembly (will not include the mate-pair reads), but Pilon seems very slow for this purpose considering this is a 2Gbp genome [Right now we are trying to split up the genome into chunks to see how well that Pilon performs in that regard].  Does it seem reasonable to use minimap2 to overlap the Illumina short-insert reads into a PAF and then run Racon in error correct mode? Note that I am using commit 0834442ab980b10f7b0805570d1edab19d268767 on the master branch.

**Comment by rvaser** [comment]
Hello,
today we will be releasing a new version of Racon which will support Illumina (with other stuff). And yes, you will be able to 'minimap2 -x sr' with the new version.

Best regards,
Robert

**Comment by rvaser** [comment]
You can go ahead and try refactor_v branch :)

**Comment by jelber2** [comment]
Should I rerun the PBJelly assembly through the updated version of Racon (i.e., create consensus with PacBio reads overlapping the PBJelly assembly)? Obviously, I don't need to redo the mapping of the PacBio reads to the assembly- rather redoing Racon step with newer version.

**Comment by rvaser** [comment]
I don't think it is necessary, the newer version is just faster and uses less memory. Map the Illumina reads on polished assembly and you are good to go.

**Comment by rvaser** [comment]
New version is now on master branch.
