### ISSUE TITLE
Build fails due to missing header

### ISSUE THREAD

**Issue by mmclaren42** [isovic/racon#51]
Trying to build the current version failed for me today with the error
```
/home/michael/applications/racon/vendor/thread_pool/include/thread_pool/thread_pool.hpp:67:18: error: ‘bind’ is not a member of ‘std’                                                                            
             std::bind(std::forward<T>(routine), std::forward<Ts>(params)...) 
```
Some googling led me to https://github.com/randombit/botan/issues/903 and the thought of adding `#include <functional>` to the list of included headers in the offending file `racon/vendor/thread_pool/include/thread_pool/thread_pool.hpp`, and after that I was able to compile with no error.

Perhaps this issue is compiler specific/version? I'm running Archlinux with `gcc` version is 7.3.0 and `cmake` version is 3.10.2.

**Comment by rvaser** [comment]
Fixed! Thank you for testing.

Best regards,
Robert
