### ISSUE TITLE
g++7: error: 'bind' is not a member of 'std'

### ISSUE THREAD

**Issue by sjackman** [isovic/racon#52]
`std::bind` is defined in the header `<functional>`.
See http://en.cppreference.com/w/cpp/utility/functional/bind

```
cd /tmp/racon-20180225-56119-1pc5os2/build/vendor/spoa && /usr/local/Homebrew/Library/Homebrew/shims/super/g++-7   -I/tmp/racon-20180225-56119-1pc5os2/vendor/spoa/include  -Wall -Wextra -pedantic -Wall -Wextra -pedantic -march=native -DNDEBUG   -std=gnu++11 -o CMakeFiles/spoa.dir/src/alignment_engine.cpp.o -c /tmp/racon-20180225-56119-1pc5os2/vendor/spoa/src/alignment_engine.cpp
In file included from /tmp/racon-20180225-56119-1pc5os2/vendor/thread_pool/src/thread_pool.cpp:9:0:
/tmp/racon-20180225-56119-1pc5os2/vendor/thread_pool/include/thread_pool/thread_pool.hpp: In member function 'std::future<typename std::result_of<_Functor(_ArgTypes ...)>::type> thread_pool::ThreadPool::submit_task(T&&, Ts&& ...)':
/tmp/racon-20180225-56119-1pc5os2/vendor/thread_pool/include/thread_pool/thread_pool.hpp:67:18: error: 'bind' is not a member of 'std'
             std::bind(std::forward<T>(routine), std::forward<Ts>(params)...)
```

**Comment by sjackman** [comment]
This issue was fixed in this commit: https://github.com/rvaser/thread_pool/commit/712c5f362d8f135505098741cf54985d075d8a58#diff-f1c719126d482c5d6a608d038504e5ba

Could you please tag a stable release 1.0.1 of Racon to resolve this issue? I'm working on updating the formula for Brewsci/bio (Homebrew/Linuxbrew). See https://github.com/brewsci/homebrew-bio/pull/65

**Comment by rvaser** [comment]
Would you mind if I update the 1.0.0 version with the latest commit? Or does it have to be a new release?

**Comment by sjackman** [comment]
A new release is usually preferred. Changing the SHA-256 of a release that's already out sets of alarm bells for packages, such as Debian, Homebrew, et c.

**Comment by rvaser** [comment]
Done!

**Comment by sjackman** [comment]
Thanks!
