### ISSUE TITLE
Release a tarball that includes submodules

### ISSUE THREAD

**Issue by sjackman** [isovic/racon#53]
Consider adding a tarball to the releases page that includes the required submodules. As a bonus, though GitHub does not track clones, it does track downloads of assets like tarballs on the releases page, which can be useful analytics when reporting the impact of your tools.

**Comment by rvaser** [comment]
Done! Could you please tell me where exactly does GitHub track downloads of releases? I can't manage to find it anywhere.

**Comment by sjackman** [comment]
GitHub does track Git clones, but only for the last two weeks, no historical data.
See https://github.com/isovic/racon/graphs/traffic

Asset download counts can be accessed through the GitHub API:
```
curl https://api.github.com/repos/isovic/racon/releases | egrep -w '"name"|"download_count"'
```
See https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Comment by rvaser** [comment]
Thank you for the info! I added tarballs to all releases.

**Comment by sjackman** [comment]
Thanks, Robert!

**Comment by druvus** [comment]
thanks @rvaser and @sjackman
