### ISSUE TITLE
terminate called after throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by gabyrech** [isovic/racon#57]
Hello!
I am getting this error:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
```
My OS is Ubuntu 14.04. 

```
$ cmake --version
cmake version 3.10.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ gcc
gcc             gcc-4.8         gcc-ar          gcc-ar-4.8      gcc-nm          gcc-nm-4.8      gcc-ranlib      gcc-ranlib-4.8
```
Thanks!
Gabriel

**Comment by rvaser** [comment]
Hi Gabriel,
please run gcc --version and paste the result. Might be a bug with a specific gcc version..

Best regards,
Robert

**Comment by gabyrech** [comment]
```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Thanks Robert!

**Comment by rvaser** [comment]
Try adding `-Wl,--no-as-needed` to CMakeLists.txt at line 8 after `-pedantic`. Run cmake and compile with make.

**Comment by rvaser** [comment]
As it is a compiler specific bug I won't add the flags to master branch. You can either update your compiler to 4.8.5 or have this fix in your local installation :)

Best,
Robert

**Comment by divyakundala** [comment]
@rvaser I face the similar issue while executing the exe from the cmake. 

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted

My gcc version is:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Cmake version is:
cmake3 version 3.17.3

As per you suggestion in this post, I tried to add flags in the CMakeLists.txt but the error still persists. Can you please assist me on this?

**Comment by rvaser** [comment]
Hi @divyakundala,
which version of Racon are you using?

Best regards,
Robert

**Comment by divyakundala** [comment]
Hi @rvaser ,

I don't have racon installed in my system.

racon --version
-bash: racon: command not found

**Comment by rvaser** [comment]
Could you please paste all the commands you used for compilation? On the other hand, you can always use Racon from bioconda.

**Comment by Jnbzr** [comment]
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
how to solve
