### ISSUE TITLE
Test failing with 1.01

### ISSUE THREAD

**Issue by ebioman** [isovic/racon#59]
Hello
Is it possible that the tests are not adapted to your new structure in version 1.0.1 compared to 0.5 ?
I tried to invoke `make test` which resulted in the following errors:

<pre><code>
+ make test
+ exit 0
Processing files: Vcluster-racon-1.0.1-1.el7.x86_64
error: File not found: /builddir/build/BUILDROOT/Vcluster-racon-1.0.1-1.el7.x86_64/software/SequenceAnalysis/SequenceAlignment/racon/1.0.1/codebase
error: File not found: /builddir/build/BUILDROOT/Vcluster-racon-1.0.1-1.el7.x86_64/software/SequenceAnalysis/SequenceAlignment/racon/1.0.1/scripts
error: File not found: /builddir/build/BUILDROOT/Vcluster-racon-1.0.1-1.el7.x86_64/software/SequenceAnalysis/SequenceAlignment/racon/1.0.1/test-data
error: File not found: /builddir/build/BUILDROOT/Vcluster-racon-1.0.1-1.el7.x86_64/software/SequenceAnalysis/SequenceAlignment/racon/1.0.1/example*.sh
Executing(%doc): /bin/sh -e /software/var/tmp/rpm-tmp.3qt8DK
</code></pre>

This indicates still the old directory structure with `codebase` instead of `vendor` and `scripts` which is absent now. Or do you invoke tests differently ?

**Comment by rvaser** [comment]
Hello,
you can build unit tests by adding `-Dracon_build_tests=ON` into your `cmake` command and compile it with `make`. This will create a binary `racon_test` into the `bin` folder. The program runs without any parameters and reads sample data stored in `test/data`.

Best regards,
Robert

**Comment by ebioman** [comment]
Thanks, everything is working fine now. I realized now that the error messages where actually down-stream of the tests.
