### ISSUE TITLE
racon crashes on MAP006-1 miniasm contigs

### ISSUE THREAD

**Issue by lexnederbragt** [isovic/racon#6]
I am trying to run miniasm + racon on the E. coli K-12 MG1655 SQK-MAP006-1 as described in your preprint. I have racon crashing on it (first consensus step). I did the following. Note that I use the latest miniasm and minimap (still the same git commits as listed in your paper) as well as the latest racon (commit ID 6a4bd97385).

```
READS=MAP006-1_2D_pass.fasta #http://nanopore.s3.climb.ac.uk/MAP006-1_2D_pass.fasta
PREFIX=MAP006-1
../../../src/minimap/minimap -Sw5 -L100 -m0 -t8 ${READS} ${READS} | gzip -1 >${PREFIX}.paf.gz
../../../src/miniasm/miniasm -f ${READS} ${PREFIX}.paf.gz > ${PREFIX}.gfa
# Convert to fasta
head -n 1 ${PREFIX}.gfa | awk '{print ">"$2; print $3}' >${PREFIX}.utg.fasta
```
I then used a script to run racon:

```
prefix=MAP006-1
reads=MAP006-1_2D_pass.fasta
assembly=${prefix}.utg.fasta
mapped=${prefix}.utg_reads_mapped1.paf
consensus=${prefix}.utg_reads_racon1.fasta

# programs
minimap=../../../src/minimap/minimap
racon=../../../src/racon/bin/racon

set -x

# map
${minimap} ${assembly} ${reads} > ${mapped}

# consensus
${racon} -t 8 ${reads} ${mapped} ${assembly} ${consensus}
```

As a result, these commands were run:

```
../../../src/minimap/minimap MAP006-1.utg.fasta SQK-MAP006-1/MAP006-1_2D_pass.fasta
```

This finished fine and resulted in a 5.5M .paf file.
 
```
../../../src/racon/bin/racon -t 8 SQK-MAP006-1/MAP006-1_2D_pass.fasta MAP006-1.utg_reads_mapped1.paf MAP006-1.utg.fasta MAP006-1.utg_reads_racon1.fasta
[14:00:10 main] Using PAF for input alignments. (MAP006-1.utg_reads_mapped1.paf)
[14:00:10 main] Loading reads.
[14:00:12 main] Hashing qnames.
[14:00:12 main] Parsing the PAF file.
[14:00:12 main] Filtering overlaps.
[14:00:12 main] Aligning overlaps.

[14:00:12 AlignMHAP] Aligning overlap: 5 / 24770 (0.02%), skipped 0 / 24770 (0.00%)run_racon.sh: line 17: 96950 Segmentation fault      (core dumped) ${racon} -t 8 ${reads} ${mapped} ${assembly} ${consensus}
```

What could have gone wrong?

**Comment by isovic** [comment]
Hi Lex,
I see you're using reads in FASTA format, but Racon expects quality values. Can you try supplying it with a corresponding FASTQ file?
Let me know how it goes!
Best regards,
Ivan.

**Comment by lexnederbragt** [comment]
I will try - currently struggling to get the fastq out of the raw file but that will probably be solved soon.

**Comment by isovic** [comment]
Hi Lex,
here's the dataset we used in case it saves you some time and trouble: https://dl.dropboxusercontent.com/u/39696217/ecoli_map006_ont_reads.fastq.tar.gz
Do let me know when you download it so I can free-up the space.
Best regards,
Ivan.

**Comment by lexnederbragt** [comment]
Thanks! I got the file and racon now happily uses the fastq reads.
