### ISSUE TITLE
Unaligned PAF vs aligned PAF vs SAM

### ISSUE THREAD

**Issue by sjackman** [isovic/racon#63]
I'm polishing Miniasm and Canu assemblies of Nanopore data using Racon. I'm mapping the raw reads to the assembly with Minimap2. Do you expect Racon to work better with unaligned PAF (`minimap2` default), aligned PAF (`minimap2 -c`) or SAM (`minimap2 -a`), or does it matter?

**Comment by rvaser** [comment]
Aligned PAF is not supported, minimap2 -a might bit a bit faster and maybe yield better results.

**Comment by sjackman** [comment]
Thanks!
