### ISSUE TITLE
Racon generated an error telling "terminate called after throwing an instance of 'std::system_error'"

### ISSUE THREAD

**Issue by Jung19911124** [isovic/racon#65]
Hi.

I just started using RACON to call consensus sequence of a genome.
But I get the following error:

```
terminate called after throwing an instance of 'std::system_error'
what():  Enable multithreading to use std::thread: Operation not permitted
zsh: abort      racon reads.fq mapped.paf contigs.fasta
```

My system is:
- ubuntu 14.04
- cmake 3.11
- gcc 4.8
- clang 3.4

Is anyone encountering the same problem? What do I have to do?
Thanks.

**Comment by rvaser** [comment]
Hello,
it is a gcc bug. You can circumvent this by adding `-Wl,--no-as-needed` at end of the following flag list https://github.com/isovic/racon/blob/master/CMakeLists.txt#L8 and run `cmake` plus `make` afterwards. Or update your compiler.

Best regards,
Robert

**Comment by Jung19911124** [comment]
Thanks Robert,
your suggestion really worked.
Now I can run Racon without any error.

Best regards,
Jung
