### ISSUE TITLE
racon does not manage fastq files with multiple-line read sequence

### ISSUE THREAD

**Issue by jeanlain** [isovic/racon#67]
When specifying a fastq with line returns within sequences/quality data, racon would tell:
> [bioparser::FastqParser] error: invalid file format!

although line returns within read sequences are perfectly valid in fastq, AFAIK.

**Comment by rvaser** [comment]
Hello,
although it is allowed to wrap sequence and quality strings in FASTQ format, it complicates parsing and we decided against it (only 4 lines per read are supported).

Best regards,
Robert

**Comment by rvaser** [comment]
@jeanlain, is the wrapping really necessary? Are any new FASTQ files generated with either NGS or TGS wrapped?

**Comment by jeanlain** [comment]
seqtk subseq generates wrapped fastq by default

**Comment by rvaser** [comment]
I'll see if it isn't a big nuisance.

**Comment by rvaser** [comment]
Released in version `1.3.0`.

**Comment by jeanlain** [comment]
Great, thanks
