### ISSUE TITLE
Job Killed (memory swapping instead of use of free ram ?)

### ISSUE THREAD

**Issue by agroppi** [isovic/racon#7]
Hi

I'm trying to run your script on a vegetal genome (circa 600 Mb)
The input files were generated by using minimap and miniasm as recommanded.
But when I want to run racon, I have this error : 

```
racon: Mon Sep 19 14:53:43 CEST 2016
[14:53:49 main] Using PAF for input alignments. (/mnt/cbib/Vitireseq/Racon_assembly_Vitireseq_random_18_SMRT_5kb/vriparia_racon_random_18_smrt_5kb_reads.paf)
[14:53:49 main] Loading reads.
[15:00:07 main] Hashing qnames.
[15:00:12 main] Parsing the overlaps file.
/var/lib/torque/mom_priv/jobs/33221.jarvis.SC: line 72: 51733 Killed                  racon -v 9 -t 8 $READS $OVERLAPS_PAF $RAW_CONTIGS $PBS_O_WORKDIR/Racon_assembly_Vitireseq_random_18_SMRT_5kb/vriparia_racon_random_18_smrt_5kb_reads_consensus.fasta
Exit Code: 137
Date fin: Mon Sep 19 15:34:31 CEST 2016
Job finished
```

I have tried to use the verbose debug option (-v 9) but it doesn't work

Thanks for your help

Regards

Alexis

**Comment by rvaser** [comment]
Hello Alexis,

could you please tell us the amount of RAM you have on your machine,  size of the FASTQ file containing reads, size of the GFA file containing the backbone sequence, size of the PAF file containing read-to-backbone mappings and if you are using the latest version of Racon?

Thank you for using Racon and sorry for the delayed response.

Best regards,
Robert

**Comment by agroppi** [comment]
Hi Robert,

RAM : 512 Gb
Fastq file  : 42 Gb
PAF file : 171 Gb

@rvaser by "backbone sequences" you mean the gfa or the fasta file containing the raw contigs ?
GFA File : 569 Gb
Fasta file : 558 Gb

Thanks for your help

Alexis

**Comment by rvaser** [comment]
Hi Alexis,
do you really have 600 **G**b of raw contigs? Or should that be 600 **M**b? Can you please confirm that the PAF file contains mappings between reads and the raw contigs (it kinda looks big).

Best regards,
Robert

**Comment by agroppi** [comment]
Yes sorry for the typo (cut and paste ... :/ )
It's 600 **M**b
Here is my whole script
Thanks
[Script.zip](https://github.com/isovic/racon/files/485031/Script.zip)

**Comment by rvaser** [comment]
Hi Alexis,
you are missing a step between miniasm and racon. You need to use minimap to map all reads to raw contigs with the following command:

`READS_TO_CONTIGS_OVERLAPS="$PBS_O_WORKDIR/Racon_assembly_Vitireseq_random_18_SMRT_5kb/vriparia_racon_random_18_smrt_5kb_reads_vs_raw_contigs.paf"`
`minimap -Sw5 -L100 -m0 -t8 $READS $RAW_CONTIGS > $READS_TO_CONTIGS_OVERLAPS`

and afterwards you should call racon as:

`racon -t 8 $READS $READS_TO_CONTIGS_OVERLAPS $RAW_CONTIGS $PBS_O_WORKDIR/Racon_assembly_Vitireseq_random_18_SMRT_5kb/vriparia_racon_random_18_smrt_5kb_reads_consensus.fasta`

If you need more help or encounter any other problems, feel free to contact us again. We would love to hear if you manage to assemble your data :)

Best regards,
Robert

**Comment by agroppi** [comment]
OK, Many thanks.
I'll try and  I will keep you informed

Cheers from Bordeaux (France)

**Comment by agroppi** [comment]
Hi Robert,

The process goes now to the end without error, but It produces no consensus.
In the log (here provided) 
For the minimap step : 0 alignments for each contig
and for the racon step : 0 overlaps for each contig

Any idea ?

Thanks again

Alexis
[Log.zip](https://github.com/isovic/racon/files/485893/Log.zip)

**Comment by rvaser** [comment]
Hi Alexis,
is the file "vriparia_racon_random_18_smrt_5kb_reads_vs_raw_contigs.paf" empty? If it is, the cause is probably in minimap argument order. The first argument should be target sequences, i.e. raw contigs, and the second should be query sequences, i.e. reads. The hopefully valid command is bellow:

`minimap -Sw5 -L100 -m0 -t8 $RAW_CONTIGS $READS > $READS_TO_CONTIGS_OVERLAPS`

Best regards,
Robert

**Comment by agroppi** [comment]
Hi Robert,
Yes the file vriparia_racon_random_18_smrt_5kb_reads_vs_raw_contigs.paf was empty
I have corrected the command line in minimap
Answer tomorrow morning ...

Best regards

Alexis

**Comment by agroppi** [comment]
Hi Robert,
Racon has worked perfectly.
The number of contigs is still to high to my taste, but it's not the fault of your script ;)
I will try now to scaffold and/or merge several assemblies to improve that.

Thanks again for your help

Best regards

Alexis

**Comment by rvaser** [comment]
Hi Alexis,
I am glad it worked, feel free to contact us for help anytime :)

Best regards,
Robert
