### ISSUE TITLE
Racon instead Sparc

### ISSUE THREAD

**Issue by mictadlo** [isovic/racon#78]
Hi,
Did anyone run racon on DBG2OLC output instead of [Sparc](https://github.com/yechengxi/DBG2OLC/issues/46)?

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
we did a comparison between Sparc and Racon in our paper (https://doi.org/10.1101/gr.214270.116), although that was with miniasm raw assembly. Haven't tried it on DBG2OLC output.

Best regards,
Robert

**Comment by mictadlo** [comment]
Do you think these commands are correct to run racon?

```
DBG2OLC KmerCovTh 2 AdaptiveTh 0.01 MinOverlap 20 RemoveChimera 1 Contigs Contigs-1000.txt k 17 f input.fasta

cat Contigs-1000.txt input.fasta > ctg_pb.fasta

# Correction 1 
source activate minimap2
minimap2 -t 8 -ax map-pb \
    backbone_raw.fasta \
    ctg_pb.fasta > output.gfa1.sam

source activate racon 
racon -t 8 \ 
    ctg_pb.fasta \ 
    output.gfa1.sam \ 
    backbone_raw.fasta > output.racon1.fasta 
 
# Correction 2 
source activate minimap2 
minimap2 -t 8 -ax map-pb \ 
    output.racon1.fasta \ 
    ctg_pb.fasta > output.gfa2.sam 
 
source activate racon 
racon -t 8 \ 
    ctg_pb.fasta \ 
    output.gfa2.sam \ 
    output.racon1.fasta > output.racon2.fasta 
```

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
what is stored in `input.fasta` and what in `backbone_raw.fasta`?

Best regards,
Robert

**Comment by mictadlo** [comment]
- `input.fasta` contain the raw PacBio reads.
- `backbone_raw.fasta` is DBG2OLC output.
- `Contigs-1000.txt` is the Illumina assembly.

**Comment by rvaser** [comment]
Hi Michal,
the commands look fine but I am not sure what the goal is by using Illumina assembly in polishing. If the assembly obtained from DBG2OLC is not polished, you can run two iterations of racon with PB reads and one iteration with Illumina reads (not Illumina contigs, as they will have much lesser coverage). If the DBG2OLC assembly was polished with Sparc, you can run one iteration of racon with Illumina reads.

Best regards,
Robert

**Comment by rvaser** [comment]
Hi Michal,
if you have done everything up to step 2 of the DBG2OLC pipeline, use only the PB reads to polish the backbone. Optionally, you can polish with Illumina afterwards.

Best regards,
Robert

**Comment by mictadlo** [comment]
Hi Robert,
Do you think the command for minimap and racon are correct?

```
DBG2OLC KmerCovTh 2 AdaptiveTh 0.01 MinOverlap 20 RemoveChimera 1 Contigs sparse_pregraph.contig-1000.fasta k 17 f contamination_unmapped-5k.fasta

# Correction 1
source activate minimap2
minimap2 -t 8 -ax map-pb \
    backbone_raw.fasta \
    contamination_unmapped-5k.fasta > output.gfa1.sam

source activate racon
racon -t 8 \
    contamination_unmapped-5k.fasta \
    output.gfa1.sam \
    backbone_raw.fasta > output.racon1.fasta

# Correction 2
source activate minimap2
minimap2 -t 8 -ax map-pb \
    output.racon1.fasta \
    contamination_unmapped-5k.fasta > output.gfa2.sam

source activate racon
racon -t 8 \
    contamination_unmapped-5k.fasta \
    output.gfa2.sam \
    output.racon1.fasta > output.racon2.fasta
```

Thank you in advance,

Best wishes,

Michal

**Comment by mictadlo** [comment]
Thank you.

**Comment by mictadlo** [comment]
What is the minimum PacBio reads coverage to run Racon?

Thank you in advance.

Michal
