### ISSUE TITLE
Error: unequal lengths in sequence and overlap file for sequence

### ISSUE THREAD

**Issue by chenshixuan** [isovic/racon#80]
Hi，
   Fist, I   use Minimap && Miniasm to  assebly work with the raw  nanopore reads, here I had a assembly-result . Then I used Canu to corret and trim the nanopore raw data,then transfer the trimed fasta to fastq format. When I  used the fastq format trimed reads to polish the assembly-result, The error message is"error: unequal lengths in sequence and overlap file for sequence ". How to solve the problem ? Could you give me some suggestions? Thank you very much.
Best,
Shixuan Chen

**Comment by chenshixuan** [comment]
Hi，
  I have  solved the problem  ，Just make the reads Id Uniq will be done,Thank you .

**Comment by rvaser** [comment]
Hello,
is it still not working or did you reopen this issue by accident?

Best regards,
Robert
