### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by weiminlee1** [isovic/racon#82]
Dear sir:
my gcc version is 4.9.0 and cmake version is 3.11.4. i followed the installation command to install racon, however, when i processed the make step, the error appeared as follows. And i am a fresher in bioinformatics, would you mind telling me the methods to solve this problem. 
i am look forward to hear from you soon.
thank you
weimin

c/alignment_engine.cpp:11:
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/include/spoa/alignment_e                                                               ngine.hpp:24: error: expected nested-name-specifier before ‘Alignment’
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/include/spoa/alignment_e                                                               ngine.hpp:24: error: ‘Alignment’ has not been declared
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/include/spoa/alignment_e                                                               ngine.hpp:24: error: expected ‘;’ before ‘=’ token
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/include/spoa/alignment_e                                                               ngine.hpp:24: error: expected unqualified-id before ‘=’ token
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/include/spoa/alignment_e                                                               ngine.hpp:36: error: ‘Alignment’ does not name a type
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/include/spoa/alignment_e                                                               ngine.hpp:39: error: ‘Alignment’ does not name a type
In file included from /public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/sr                                                               c/alignment_engine.cpp:11:
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/sisd_alignment_engin                                                               e.hpp:29: error: expected ‘;’ before ‘override’
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/sisd_alignment_engin                                                               e.hpp:31: error: ‘Alignment’ does not name a type
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/sisd_alignment_engin                                                               e.hpp:42: error: ‘Alignment’ does not name a type
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/sisd_alignment_engin                                                               e.hpp:49: error: expected ‘;’ before ‘noexcept’
In file included from /public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/sr                                                               c/alignment_engine.cpp:12:
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/simd_alignment_engin                                                               e.hpp:29: error: expected ‘;’ before ‘override’
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/simd_alignment_engin                                                               e.hpp:31: error: ‘Alignment’ does not name a type
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/simd_alignment_engin                                                               e.hpp:43: error: expected constructor, destructor, or type conversion before ‘align                                                               ’
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/simd_alignment_engin                                                               e.hpp:52: error: expected initializer before ‘noexcept’
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/alignment_engine.cpp                                                               : In function ‘std::unique_ptr<spoa::AlignmentEngine, std::default_delete<spoa::Ali                                                               gnmentEngine> > spoa::createAlignmentEngine(spoa::AlignmentType, int8_t, int8_t, in                                                               t8_t)’:
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/alignment_engine.cpp                                                               :39: error: ‘nullptr’ was not declared in this scope
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/alignment_engine.cpp                                                               : At global scope:
/public1/home/stu_liuyanhui/tools/racon-v1.3.1/vendor/spoa/src/alignment_engine.cpp                                                               :52: error: ‘Alignment’ does not name a type
make[2]: *** [vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o] Error 1
make[1]: *** [vendor/spoa/CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

**Comment by rvaser** [comment]
Hello Weimin,
I think that cmake picked up another compiler which has a lower version. Run `which gcc` and use the path you get while running cmake `cmake -DCMAKE_C_COMPILER=<paste path here> ..`.

Best regards,
Robert

**Comment by weiminlee1** [comment]
Hello Robert,
thank you for your help firstly. I followed your instruction, but new problems still exist. sorry to bother you again.

Weimin


Scanning dependencies of target spoa
[ 61%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/alignment_engine.cpp.o
[ 64%] Building CXX object vendor/spoa/CMakeFiles/spoa.dir/src/graph.cpp.o
/tmp/ccTXjwsu.s: Assembler messages:
/tmp/ccTXjwsu.s:743: Error: no such instruction: `shlx %rax,%rdx,%rdx'
/tmp/ccTXjwsu.s:998: Error: no such instruction: `shlx %rax,%rdx,%rdx'
make[2]: *** [vendor/spoa/CMakeFiles/spoa.dir/src/graph.cpp.o] Error 1
make[1]: *** [vendor/spoa/CMakeFiles/spoa.dir/all] Error 2
make: *** [all] Error 2

**Comment by rvaser** [comment]
Hi Weimin,
it seems that your assembler is out of date. You can either update it or you can try adding 
 `-DCMAKE_CXX_FLAGS="-mno-avx2"` while running cmake.

Best regards,
Robert

**Comment by weiminlee1** [comment]
Hello Robert,
thank you for your instruction anyway. I tried your recommend, but install unsuccessfully.
Finally, I used BIOCONDA to install racon successfully.

Best wishes,
Weimin
