### ISSUE TITLE
When to stop polishing? 

### ISSUE THREAD

**Issue by apredeus** [isovic/racon#83]
Hello all, 

I was wondering if there's a good criterion on when do you stop polishing? I've done 5 rounds and the sequences are still changing, there's a little bit of improvement when I evaluate the genomes with BUSCO, but not a lot. 

I've seen suggestions to sum up all of the mapping qualities from the SAM file. Should percent of successfully mapped reads also be an indication?

Any suggestions are welcome.

**Comment by rvaser** [comment]
Hello,
it is hard to tell what is the optimal number of iterations. Unicycler polishes with racon until no changes are introduced (if I recall correctly) which can take some time. We use two iterations as a speed/accuracy tradeoff. Number of mapped sequences could be a stopping criterion, bu we have not played with it. If you have SGS data, two iterations of TGS data is enough prior SGS polishing.

Best regards,
Robert

**Comment by apredeus** [comment]
Thank you!

**Comment by mictadlo** [comment]
Hi,
Do you have a script which runs Racon until no changes can be seen or what would be the best way to check it?

Does `--include-unpolished` should be used for each round and why unpolished contigs are removed by default?

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Unfortunately not. You could ask Ryan Wick (author of Unicycler) to help you extract this piece of code from his software.

Unpolished sequences are removed as they do not have enough reads covering them (they are most probably of poor quality).

Best regards,
Robert

**Comment by mictadlo** [comment]
Do you think I can run racon without `--include-unpolished` with only 7x coverage (nonopore)?

**Comment by rvaser** [comment]
I am not sure, you certainly can try and see for yourself :)

**Comment by mictadlo** [comment]
What is the minimum coverage necessary for Racon? I should have mentioned that I used a Hybrid Assembly approach (SparseAssembler and DBG2OLC)?

**Comment by rvaser** [comment]
At least 3 reads have to cover a window (of 500bp) so that the polishing procedure is evoked. If you only have TGS data, I guess you need at least 20x for decent accuracy. If you are using hybrid assemblers, polish your assembly by passing NGS data to Racon.

**Comment by mictadlo** [comment]
Ngs reads or ngs contigs? Should I merge them with tgs?

**Comment by rvaser** [comment]
Use only NGS reads to polish your contigs :)

**Comment by mictadlo** [comment]
Hi,
Below, I have tried to apply paired-end data to Racon but I am not quite sure wether I am on the right track?

```
# Correction 1
source activate bwa
bwa mem \
backbone_raw.fasta $r1 $r2 \
-t 12  read_R1.fq read_R2.fq | samblaster -r | samtools view -@ 12 -bSh -f 0x2 -F 2316 - | samtools fixmate - - | samtools sort -@ 12 - -o ${3}/${output}.sorted.dedup.bam

samtools merge output.gfa1.sam *.bam --output-fmt sam

source activate racon
racon -t 32 \
    3rd-1k.fasta \    ?????
    output.gfa1.sam \
    backbone_raw.fasta | gzip > output.racon1.fasta.gz

# Correction 2
source activate bwa
bwa mem \
backbone_raw.fasta $r1 $r2 \
-t 12  read_R1.fq read_R2.fq | samblaster -r | samtools view -@ 12 -bSh -f 0x2 -F 2316 - | samtools fixmate - - | samtools sort -@ 12 - -o ${3}/${output}.sorted.dedup.bam
samtools merge output.gfa2.sam *.bam --output-fmt sam

source activate racon
racon -t 32 \
    3rd-1k.fasta \ ??????
    output.gfa2.sam \
    output.racon1.fasta | gzip > output.racon2.fasta.gz
```

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
you have to join paired ends into one file (in which all sequences need to have an unique identifier up to the first white space, see https://github.com/isovic/racon/issues/68#issuecomment-386223150 for a script that does that), map them to the backbone and then invoke racon. Something like this:

```bash
// join reads with the above script

// align them to backbone
minimap2 -t 12 -ax sr bacbone_raw.fasta reads.fq > output.sam

// invoke racon
racon -t 12 reads.fq output.sam backbone_raw.fasta
```

Best regards,
Robert

**Comment by mictadlo** [comment]
Hi Robert,
After running `minimap2 -t 12 -ax sr bacbone_raw.fasta reads.fq | gzip - > output.sam.gz` could I additionally align the Nanopore reads `minimap2 -t 32 -ax map-ont backbone_raw.fasta 3rd-1k.fastq | gzip - > output.gfa1.sam`. Next, to merge the both files with `cat *.sam | samblaster -r | samtools view -@ 12 -h -F 2316 - | gzip - > all.sorted.dedup.sam.gz`. Finally, to run `racon -t 12 reads.fq all.sorted.dedup.sam.gz backbone_raw.fasta`?

The other question is after running your merge pair-end script could convert its output to FASTA file with `bioawk -c fastx '{print ">"$name; print $seq}' input.fastq > output.fa` and do all the above steps with FASTA rather than FASTQ?

Thank you in advance,

Michal

**Comment by mictadlo** [comment]
Hi Robert,
After running your merge pair-end script and `minimap2 -t 12 -ax sr backbone_raw.fasta reads.fq | gzip - > output.sam.gz` would it possible to align additionally the ONT reads with `minimap2 -t 32 -ax map-ont backbone_raw.fasta 3rd-1k.fastq | gzip - > output.gfa1.sam.gz`. Next, to merge the both SAM files with `zcat *.sam.gz | samblaster -r  |  samtools view -@ 12 -h -F 2316 - | gzip - > all.dedup.sam.gz` and FASTQ files with `cat 3rd-1k.fastq reads.fastq | gzip - > reads-andONT.fastq.gz `. Finally, to run `racon -t 12 reads-andONT.fastq.gz output.sam backbone_raw.fasta`?

Another question is whether after running your merge pair-end script the output could be converted to FASTA file with `bioawk -c fastx '{print ">"$name; print $seq}' input.fastq > output.fa` and used in above way rather than with FASTQ file?

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
I am not sure if joining ONT and Illumina data will work because of a heuristic for consensus trimming. Why do you need to join these read sets? I do not think that ONT data will help here.

Yes, you can transform FASTQ to FASTA and just run racon with FASTA.

Best regards,
Robert

**Comment by mictadlo** [comment]
Hi Robert,
I thought ONT plus Illumina would increase the coverage. Could you please check whether the below racon pipeline is correct?

```
# Correction 1
source activate minimap2
minimap2 -t 12 -ax sr \
    backbone_raw.fasta \
    reads.fa | gzip - > output.gfa1.sam.gz

source activate racon
racon -t 32 \
    reads.fa \
    output.gfa1.sam.gz \
    backbone_raw.fasta > output.racon1.fasta

# Correction 2
source activate minimap2
minimap2 -t 32 -ax map-pb \
    output.racon1.fasta \
    ctg_pb.fasta | gzip - > output.gfa2.sam.gz

source activate racon
racon -t 32 \
    ctg_pb.fasta \
    output.gfa2.sam.gz \
    output.racon1.fasta > output.racon2.fasta
```

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
what is in `ctg_pb.fasta`? I would advise against polishing first with Illumina and then with PB/ONT. Commands are correct though.

Best regards,
Robert

**Comment by mictadlo** [comment]
Hi Robert,
I am sorry, I forgot to change the 2nd correction step. Could you please check whether the updated commands following your recommendation?

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Where are the updated command?

**Comment by mictadlo** [comment]
I am sorry please find below:

```
#!/bin/bash
# usage: sh racon_pbs.sh ../fastp-filtered-merged4racon/merged_R1_R2.fa
cat << EOF  |qsub
#!/bin/bash -l
#PBS -N racon
#PBS -l walltime=150:00:00
#PBS -j oe
#PBS -l mem=400G
#PBS -l ncpus=32
#PBS -M m.lorenc@qut.edu.au

cd \$PBS_O_WORKDIR

# Correction 1
conda activate minimap2
minimap2 -t 32 -ax sr \
    backbone_raw.fasta \
    $1 | gzip - > output.gfa1.sam.gz
conda deactivate

conda activate racon
racon -t 32 \
    $1 \
    output.gfa1.sam.gz \
    backbone_raw.fasta > output.racon1.fasta
conda deactivate

# Correction 2
conda activate minimap2
minimap2 -t 32 -ax sr \
    output.racon1.fasta \
    $1 | gzip - > output.gfa2.sam.gz
conda deactivate

conda activate racon
racon -t 32 \
    $1 \
    output.gfa2.sam.gz \
    output.racon1.fasta > output.racon2.fasta
conda deactivate

rm output.gfa1.sam.gz output.gfa2.sam.gz output.racon1.fasta

source activate dbg2olc
abyss-fac output.racon2.fasta

EOF
```

I also updated your script so it can read `gz` files and convert the output to FASTA 

```
#!/usr/bin/env python

#USAGE: python3 shuffle_pairs_fastq.py input_1.fastq.gz input2.fastq.gz > input12.fasta


from __future__ import print_function
import sys
import gzip

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def parse_file(file_name, read_set):
    line_id = 0
    name = ''
    data = ''
    qual = ''
    valid = False
    with (gzip.open(file_name, 'rt')) as f:
        for line in f:
            if (line_id == 0):
                if (valid):
                    if (len(name) == 0 or len(data) == 0 or len(data) != len(qual)):
                        eprint('File is not in FASTQ format')
                        sys.exit(1)
                    valid = False
                    if (name in read_set):
                        print(name + '2')
                    else:
                        read_set.add(name)
                        print(name + '1')
                    print(data)
                name = line.rstrip().split(' ')[0].replace('@','>',1)
                data = ''
                qual = ''
                line_id = 1
            elif (line_id == 1):
                if (line[0] == '+'):
                    line_id = 2
                else:
                    data += line.rstrip()
            elif (line_id == 2):
                qual += line.rstrip()
                if (len(qual) >= len(data)):
                    valid = True
                    line_id = 0

    if (valid):
        if (len(name) == 0 or len(data) == 0 or len(data) != len(qual)):
            eprint(len(name), len(data), len(qual))
            eprint('File is not in FASTQ format')
            sys.exit(1)
        if (name in read_set):
           print(name + '2')
        else:
           read_set.add(name)
           print(name + '1')
        print(data)

if __name__ == '__main__':

    read_set = set()

    if (len(sys.argv) > 1):
        parse_file(sys.argv[1], read_set)
    if (len(sys.argv) > 2):
        parse_file(sys.argv[2], read_set)
```
Does Racon support FASTA file compressed with gzip?

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
the commands are correct. Thanks for the updated script! :) Racon supports all file types (FASTA/Q, PAF, SAM) compressed with gzip.

Best regards,
Robert

**Comment by mictadlo** [comment]
I ran the script and noticed a high memory consumption, do you really need `read_set = set()` or could it be changed to:

```
#!/usr/bin/env python

#USAGE: python3 shuffle_pairs_fastq.py input_1.fastq input2.fastq > input12.fasta


from __future__ import print_function
import sys

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def parse_file(file_name, read_number):
    line_id = 0
    name = ''
    data = ''
    qual = ''
    valid = False
    with (open(file_name)) as f:
        for line in f:
            if (line_id == 0):
                if (valid):
                    if (len(name) == 0 or len(data) == 0 or len(data) != len(qual)):
                        eprint('File is not in FASTQ format')
                        sys.exit(1)
                    valid = False
                    print(name + read_number)
                    print(data)
                    
                name = line.rstrip().split(' ')[0].replace('@','>',1)
                data = ''
                qual = ''
                line_id = 1
            elif (line_id == 1):
                if (line[0] == '+'):
                    line_id = 2
                else:
                    data += line.rstrip()
            elif (line_id == 2):
                qual += line.rstrip()
                if (len(qual) >= len(data)):
                    valid = True
                    line_id = 0

    if (valid):
        if (len(name) == 0 or len(data) == 0 or len(data) != len(qual)):
            eprint(len(name), len(data), len(qual))
            eprint('File is not in FASTQ format')
            sys.exit(1)

        print(name + read_number)
        print(data)

if __name__ == '__main__':

    if (len(sys.argv) > 1):
        parse_file(sys.argv[1], 1)
    if (len(sys.argv) > 2):
        parse_file(sys.argv[2], 2)
```
What do you think?

Thank you in advance,

Michal

**Comment by rvaser** [comment]
Hi Michal,
It looks fine to me :)

Best regards,
Robert
