### ISSUE TITLE
chimeric in window 

### ISSUE THREAD

**Issue by njaupan** [isovic/racon#87]
Dear Ivan,
I have used the command below for a draft genome that is 130x coverage assembled by smartdenovo,
~bin/racon -t 12  reads reads2fasta.minimap2.sam  fasta  -w 1500 > racon.fa
and meet error like this:
[racon::Window::generate_consensus] warning: contig 0 might be chimeric in window 3!

Do you have any suggestions?

Best,
panpan

**Comment by jtoy7** [comment]
Hi Robert,

I see this thread was from a few years back, but I am getting the same warning. Is it still okay to ignore the message? I am running v1.4.13

`[racon::Window::generate_consensus] warning: contig 398 might be chimeric in window 2!`

Thanks,
Jason

**Comment by rvaser** [comment]
Hi Jason,
yes you can ignore it.

Best regards,
Robert

**Comment by jtoy7** [comment]
Great, thanks!

**Comment by emily-ap** [comment]
hello, checking in to make sure it's still okay to ignore this since it's been a few years. Thanks!
