### ISSUE TITLE
contigs numbers were reduced 

### ISSUE THREAD

**Issue by njaupan** [isovic/racon#98]
Hi,

I ran Racon on a Canu-assembled 130X plant genome. It reduced from original 530 contigs to 510 by first round Racon and to 507 contigs by second round Racon. It is weried as Racon should not change contigs number if i understand correctly. I re-run Racon three times, it didn't help. Here is the script, can you tell me why?

~/minimap2-2.12_x64-linux/minimap2 -t 12 --MD -ax map-ont canu.fa reads.fa > 1.sam
~/racon/build/bin/racon -t 12 -w 1500 reads.fa 1.sam canu.fa > racon1.fa

Best,
panpan

**Comment by rvaser** [comment]
Hello,
racon by default does not return sequences which were not polished, hence the decrease in contig number. You can retain them with the `-u (--include-unpolished)` option.

Best regards,
Robert

**Comment by njaupan** [comment]
I see, Thank you!
